/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class AnalyticServiceLogQueryRequestFilter {
    'field'?: string;
    'value'?: string;
    'not'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "not",
            "baseName": "not",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalyticServiceLogQueryRequestFilter.attributeTypeMap;
    }

    public constructor() {
    }
}
