/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { AnalyticServiceSQLQuery } from './AnalyticServiceSQLQuery.js';
import {
    AnalyticServiceSQLQueryFromJSON,
    AnalyticServiceSQLQueryFromJSONTyped,
    AnalyticServiceSQLQueryToJSON,
} from './AnalyticServiceSQLQuery.js';
import type { CommonCachePolicy } from './CommonCachePolicy.js';
import {
    CommonCachePolicyFromJSON,
    CommonCachePolicyFromJSONTyped,
    CommonCachePolicyToJSON,
} from './CommonCachePolicy.js';

/**
 * 
 * @export
 * @interface AnalyticServiceAnalyticServiceExecuteSQLBody
 */
export interface AnalyticServiceAnalyticServiceExecuteSQLBody {
    /**
     * 
     * @type {string}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    projectId?: string;
    /**
     * 
     * @type {number}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    version?: number;
    /**
     * 
     * @type {AnalyticServiceSQLQuery}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    sqlQuery?: AnalyticServiceSQLQuery;
    /**
     * 
     * @type {string}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    cursor?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    bypassCache?: boolean;
    /**
     * 
     * @type {CommonCachePolicy}
     * @memberof AnalyticServiceAnalyticServiceExecuteSQLBody
     */
    cachePolicy?: CommonCachePolicy;
}

/**
 * Check if a given object implements the AnalyticServiceAnalyticServiceExecuteSQLBody interface.
 */
export function instanceOfAnalyticServiceAnalyticServiceExecuteSQLBody(value: object): boolean {
    return true;
}

export function AnalyticServiceAnalyticServiceExecuteSQLBodyFromJSON(json: any): AnalyticServiceAnalyticServiceExecuteSQLBody {
    return AnalyticServiceAnalyticServiceExecuteSQLBodyFromJSONTyped(json, false);
}

export function AnalyticServiceAnalyticServiceExecuteSQLBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticServiceAnalyticServiceExecuteSQLBody {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'version': json['version'] == null ? undefined : json['version'],
        'sqlQuery': json['sqlQuery'] == null ? undefined : AnalyticServiceSQLQueryFromJSON(json['sqlQuery']),
        'cursor': json['cursor'] == null ? undefined : json['cursor'],
        'bypassCache': json['bypassCache'] == null ? undefined : json['bypassCache'],
        'cachePolicy': json['cachePolicy'] == null ? undefined : CommonCachePolicyFromJSON(json['cachePolicy']),
    };
}

export function AnalyticServiceAnalyticServiceExecuteSQLBodyToJSON(value?: AnalyticServiceAnalyticServiceExecuteSQLBody | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'projectId': value['projectId'],
        'version': value['version'],
        'sqlQuery': AnalyticServiceSQLQueryToJSON(value['sqlQuery']),
        'cursor': value['cursor'],
        'bypassCache': value['bypassCache'],
        'cachePolicy': CommonCachePolicyToJSON(value['cachePolicy']),
    };
}

