/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export enum AnalyticServiceSource {
    SqlEditor = 'SQL_EDITOR',
    Dashboard = 'DASHBOARD',
    AsyncTrigger = 'ASYNC_TRIGGER',
    Curl = 'CURL',
    Endpoint = 'ENDPOINT'
}
