/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnalyticServiceExecutionInfo } from '../models/AnalyticServiceExecutionInfo.js';
import { HttpFile } from '../http/http.js';

export class AnalyticServiceRerunSQLQueryResponse {
    'queueLength'?: number;
    'executionInfo'?: AnalyticServiceExecutionInfo;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queueLength",
            "baseName": "queueLength",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "executionInfo",
            "baseName": "executionInfo",
            "type": "AnalyticServiceExecutionInfo",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AnalyticServiceRerunSQLQueryResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
