/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnalyticServiceQuerySegmentationResponseResult } from './AnalyticServiceQuerySegmentationResponseResult';
import {
    AnalyticServiceQuerySegmentationResponseResultFromJSON,
    AnalyticServiceQuerySegmentationResponseResultFromJSONTyped,
    AnalyticServiceQuerySegmentationResponseResultToJSON,
} from './AnalyticServiceQuerySegmentationResponseResult';

/**
 * 
 * @export
 * @interface AnalyticServiceQueryLogMetricsResponse
 */
export interface AnalyticServiceQueryLogMetricsResponse {
    /**
     * 
     * @type {Array<AnalyticServiceQuerySegmentationResponseResult>}
     * @memberof AnalyticServiceQueryLogMetricsResponse
     */
    results?: Array<AnalyticServiceQuerySegmentationResponseResult>;
}

/**
 * Check if a given object implements the AnalyticServiceQueryLogMetricsResponse interface.
 */
export function instanceOfAnalyticServiceQueryLogMetricsResponse(value: object): boolean {
    return true;
}

export function AnalyticServiceQueryLogMetricsResponseFromJSON(json: any): AnalyticServiceQueryLogMetricsResponse {
    return AnalyticServiceQueryLogMetricsResponseFromJSONTyped(json, false);
}

export function AnalyticServiceQueryLogMetricsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticServiceQueryLogMetricsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(AnalyticServiceQuerySegmentationResponseResultFromJSON)),
    };
}

export function AnalyticServiceQueryLogMetricsResponseToJSON(value?: AnalyticServiceQueryLogMetricsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(AnalyticServiceQuerySegmentationResponseResultToJSON)),
    };
}

