/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonComputeStats } from './CommonComputeStats';
import {
    CommonComputeStatsFromJSON,
    CommonComputeStatsFromJSONTyped,
    CommonComputeStatsToJSON,
} from './CommonComputeStats';
import type { CommonMatrix } from './CommonMatrix';
import {
    CommonMatrixFromJSON,
    CommonMatrixFromJSONTyped,
    CommonMatrixToJSON,
} from './CommonMatrix';

/**
 * 
 * @export
 * @interface AnalyticServiceQuerySegmentationResponseResult
 */
export interface AnalyticServiceQuerySegmentationResponseResult {
    /**
     * 
     * @type {CommonMatrix}
     * @memberof AnalyticServiceQuerySegmentationResponseResult
     */
    matrix?: CommonMatrix;
    /**
     * 
     * @type {string}
     * @memberof AnalyticServiceQuerySegmentationResponseResult
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticServiceQuerySegmentationResponseResult
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof AnalyticServiceQuerySegmentationResponseResult
     */
    id?: string;
    /**
     * 
     * @type {CommonComputeStats}
     * @memberof AnalyticServiceQuerySegmentationResponseResult
     */
    computeStats?: CommonComputeStats;
}

/**
 * Check if a given object implements the AnalyticServiceQuerySegmentationResponseResult interface.
 */
export function instanceOfAnalyticServiceQuerySegmentationResponseResult(value: object): boolean {
    return true;
}

export function AnalyticServiceQuerySegmentationResponseResultFromJSON(json: any): AnalyticServiceQuerySegmentationResponseResult {
    return AnalyticServiceQuerySegmentationResponseResultFromJSONTyped(json, false);
}

export function AnalyticServiceQuerySegmentationResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnalyticServiceQuerySegmentationResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'matrix': json['matrix'] == null ? undefined : CommonMatrixFromJSON(json['matrix']),
        'error': json['error'] == null ? undefined : json['error'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'id': json['id'] == null ? undefined : json['id'],
        'computeStats': json['computeStats'] == null ? undefined : CommonComputeStatsFromJSON(json['computeStats']),
    };
}

export function AnalyticServiceQuerySegmentationResponseResultToJSON(value?: AnalyticServiceQuerySegmentationResponseResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'matrix': CommonMatrixToJSON(value['matrix']),
        'error': value['error'],
        'alias': value['alias'],
        'id': value['id'],
        'computeStats': CommonComputeStatsToJSON(value['computeStats']),
    };
}

