/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonRichValue } from './CommonRichValue.js';
import {
    CommonRichValueFromJSON,
    CommonRichValueFromJSONTyped,
    CommonRichValueToJSON,
    CommonRichValueToJSONTyped,
} from './CommonRichValue.js';

/**
 * 
 * @export
 * @interface CommonRichValueList
 */
export interface CommonRichValueList {
    /**
     * 
     * @type {Array<CommonRichValue>}
     * @memberof CommonRichValueList
     */
    values?: Array<CommonRichValue>;
}

/**
 * Check if a given object implements the CommonRichValueList interface.
 */
export function instanceOfCommonRichValueList(value: object): value is CommonRichValueList {
    return true;
}

export function CommonRichValueListFromJSON(json: any): CommonRichValueList {
    return CommonRichValueListFromJSONTyped(json, false);
}

export function CommonRichValueListFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonRichValueList {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(CommonRichValueFromJSON)),
    };
}

  export function CommonRichValueListToJSON(json: any): CommonRichValueList {
      return CommonRichValueListToJSONTyped(json, false);
  }

  export function CommonRichValueListToJSONTyped(value?: CommonRichValueList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'values': value['values'] == null ? undefined : ((value['values'] as Array<any>).map(CommonRichValueToJSON)),
    };
}

