/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonSegmentationQuerySelectorExprLogicExpr } from './CommonSegmentationQuerySelectorExprLogicExpr';
import {
    CommonSegmentationQuerySelectorExprLogicExprFromJSON,
    CommonSegmentationQuerySelectorExprLogicExprFromJSONTyped,
    CommonSegmentationQuerySelectorExprLogicExprToJSON,
} from './CommonSegmentationQuerySelectorExprLogicExpr';
import type { CommonSelector } from './CommonSelector';
import {
    CommonSelectorFromJSON,
    CommonSelectorFromJSONTyped,
    CommonSelectorToJSON,
} from './CommonSelector';

/**
 * 
 * @export
 * @interface CommonSegmentationQuerySelectorExpr
 */
export interface CommonSegmentationQuerySelectorExpr {
    /**
     * 
     * @type {CommonSelector}
     * @memberof CommonSegmentationQuerySelectorExpr
     */
    selector?: CommonSelector;
    /**
     * 
     * @type {CommonSegmentationQuerySelectorExprLogicExpr}
     * @memberof CommonSegmentationQuerySelectorExpr
     */
    logicExpr?: CommonSegmentationQuerySelectorExprLogicExpr;
}

/**
 * Check if a given object implements the CommonSegmentationQuerySelectorExpr interface.
 */
export function instanceOfCommonSegmentationQuerySelectorExpr(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommonSegmentationQuerySelectorExprFromJSON(json: any): CommonSegmentationQuerySelectorExpr {
    return CommonSegmentationQuerySelectorExprFromJSONTyped(json, false);
}

export function CommonSegmentationQuerySelectorExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSegmentationQuerySelectorExpr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'selector': !exists(json, 'selector') ? undefined : CommonSelectorFromJSON(json['selector']),
        'logicExpr': !exists(json, 'logicExpr') ? undefined : CommonSegmentationQuerySelectorExprLogicExprFromJSON(json['logicExpr']),
    };
}

export function CommonSegmentationQuerySelectorExprToJSON(value?: CommonSegmentationQuerySelectorExpr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'selector': CommonSelectorToJSON(value.selector),
        'logicExpr': CommonSegmentationQuerySelectorExprLogicExprToJSON(value.logicExpr),
    };
}

