/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class CommonComputeStatsClickhouseStats {
    'readRows'?: string;
    'readBytes'?: string;
    'memoryUsage'?: string;
    'queryDurationMs'?: string;
    'resultRows'?: string;
    'resultBytes'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "readRows",
            "baseName": "readRows",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "readBytes",
            "baseName": "readBytes",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "memoryUsage",
            "baseName": "memoryUsage",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "queryDurationMs",
            "baseName": "queryDurationMs",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "resultRows",
            "baseName": "resultRows",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "resultBytes",
            "baseName": "resultBytes",
            "type": "string",
            "format": "uint64"
        }    ];

    static getAttributeTypeMap() {
        return CommonComputeStatsClickhouseStats.attributeTypeMap;
    }

    public constructor() {
    }
}
