/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonSegmentationQuerySelectorExpr } from './CommonSegmentationQuerySelectorExpr.js';
import {
    CommonSegmentationQuerySelectorExprFromJSON,
    CommonSegmentationQuerySelectorExprFromJSONTyped,
    CommonSegmentationQuerySelectorExprToJSON,
    CommonSegmentationQuerySelectorExprToJSONTyped,
} from './CommonSegmentationQuerySelectorExpr.js';
import type { CommonJoinOperator } from './CommonJoinOperator.js';
import {
    CommonJoinOperatorFromJSON,
    CommonJoinOperatorFromJSONTyped,
    CommonJoinOperatorToJSON,
    CommonJoinOperatorToJSONTyped,
} from './CommonJoinOperator.js';

/**
 * 
 * @export
 * @interface CommonSegmentationQuerySelectorExprLogicExpr
 */
export interface CommonSegmentationQuerySelectorExprLogicExpr {
    /**
     * 
     * @type {Array<CommonSegmentationQuerySelectorExpr>}
     * @memberof CommonSegmentationQuerySelectorExprLogicExpr
     */
    expressions?: Array<CommonSegmentationQuerySelectorExpr>;
    /**
     * 
     * @type {CommonJoinOperator}
     * @memberof CommonSegmentationQuerySelectorExprLogicExpr
     */
    operator?: CommonJoinOperator;
}



/**
 * Check if a given object implements the CommonSegmentationQuerySelectorExprLogicExpr interface.
 */
export function instanceOfCommonSegmentationQuerySelectorExprLogicExpr(value: object): value is CommonSegmentationQuerySelectorExprLogicExpr {
    return true;
}

export function CommonSegmentationQuerySelectorExprLogicExprFromJSON(json: any): CommonSegmentationQuerySelectorExprLogicExpr {
    return CommonSegmentationQuerySelectorExprLogicExprFromJSONTyped(json, false);
}

export function CommonSegmentationQuerySelectorExprLogicExprFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSegmentationQuerySelectorExprLogicExpr {
    if (json == null) {
        return json;
    }
    return {
        
        'expressions': json['expressions'] == null ? undefined : ((json['expressions'] as Array<any>).map(CommonSegmentationQuerySelectorExprFromJSON)),
        'operator': json['operator'] == null ? undefined : CommonJoinOperatorFromJSON(json['operator']),
    };
}

  export function CommonSegmentationQuerySelectorExprLogicExprToJSON(json: any): CommonSegmentationQuerySelectorExprLogicExpr {
      return CommonSegmentationQuerySelectorExprLogicExprToJSONTyped(json, false);
  }

  export function CommonSegmentationQuerySelectorExprLogicExprToJSONTyped(value?: CommonSegmentationQuerySelectorExprLogicExpr | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expressions': value['expressions'] == null ? undefined : ((value['expressions'] as Array<any>).map(CommonSegmentationQuerySelectorExprToJSON)),
        'operator': CommonJoinOperatorToJSON(value['operator']),
    };
}

