/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommonProjectType = {
    Sentio: 'SENTIO',
    Subgraph: 'SUBGRAPH'
} as const;
export type CommonProjectType = typeof CommonProjectType[keyof typeof CommonProjectType];


export function instanceOfCommonProjectType(value: any): boolean {
    for (const key in CommonProjectType) {
        if (Object.prototype.hasOwnProperty.call(CommonProjectType, key)) {
            if (CommonProjectType[key as keyof typeof CommonProjectType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CommonProjectTypeFromJSON(json: any): CommonProjectType {
    return CommonProjectTypeFromJSONTyped(json, false);
}

export function CommonProjectTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonProjectType {
    return json as CommonProjectType;
}

export function CommonProjectTypeToJSON(value?: CommonProjectType | null): any {
    return value as any;
}

export function CommonProjectTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CommonProjectType {
    return value as CommonProjectType;
}

