/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommonCohortsFilterAggregationOperatorType = {
    Eq: 'EQ',
    Neq: 'NEQ',
    Gt: 'GT',
    Gte: 'GTE',
    Lt: 'LT',
    Lte: 'LTE',
    Between: 'BETWEEN',
    NotBetween: 'NOT_BETWEEN'
} as const;
export type CommonCohortsFilterAggregationOperatorType = typeof CommonCohortsFilterAggregationOperatorType[keyof typeof CommonCohortsFilterAggregationOperatorType];


export function instanceOfCommonCohortsFilterAggregationOperatorType(value: any): boolean {
    return Object.values(CommonCohortsFilterAggregationOperatorType).includes(value);
}

export function CommonCohortsFilterAggregationOperatorTypeFromJSON(json: any): CommonCohortsFilterAggregationOperatorType {
    return CommonCohortsFilterAggregationOperatorTypeFromJSONTyped(json, false);
}

export function CommonCohortsFilterAggregationOperatorTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonCohortsFilterAggregationOperatorType {
    return json as CommonCohortsFilterAggregationOperatorType;
}

export function CommonCohortsFilterAggregationOperatorTypeToJSON(value?: CommonCohortsFilterAggregationOperatorType | null): any {
    return value as any;
}

