/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonSystemSQLQueryAggregationAggregatePropertiesAggregationType } from './CommonSystemSQLQueryAggregationAggregatePropertiesAggregationType';
import {
    CommonSystemSQLQueryAggregationAggregatePropertiesAggregationTypeFromJSON,
    CommonSystemSQLQueryAggregationAggregatePropertiesAggregationTypeFromJSONTyped,
    CommonSystemSQLQueryAggregationAggregatePropertiesAggregationTypeToJSON,
} from './CommonSystemSQLQueryAggregationAggregatePropertiesAggregationType';

/**
 * 
 * @export
 * @interface CommonSystemSQLQueryAggregationAggregateProperties
 */
export interface CommonSystemSQLQueryAggregationAggregateProperties {
    /**
     * 
     * @type {CommonSystemSQLQueryAggregationAggregatePropertiesAggregationType}
     * @memberof CommonSystemSQLQueryAggregationAggregateProperties
     */
    type?: CommonSystemSQLQueryAggregationAggregatePropertiesAggregationType;
    /**
     * 
     * @type {string}
     * @memberof CommonSystemSQLQueryAggregationAggregateProperties
     */
    propertyName?: string;
}

/**
 * Check if a given object implements the CommonSystemSQLQueryAggregationAggregateProperties interface.
 */
export function instanceOfCommonSystemSQLQueryAggregationAggregateProperties(value: object): boolean {
    return true;
}

export function CommonSystemSQLQueryAggregationAggregatePropertiesFromJSON(json: any): CommonSystemSQLQueryAggregationAggregateProperties {
    return CommonSystemSQLQueryAggregationAggregatePropertiesFromJSONTyped(json, false);
}

export function CommonSystemSQLQueryAggregationAggregatePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSystemSQLQueryAggregationAggregateProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : CommonSystemSQLQueryAggregationAggregatePropertiesAggregationTypeFromJSON(json['type']),
        'propertyName': json['propertyName'] == null ? undefined : json['propertyName'],
    };
}

export function CommonSystemSQLQueryAggregationAggregatePropertiesToJSON(value?: CommonSystemSQLQueryAggregationAggregateProperties | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': CommonSystemSQLQueryAggregationAggregatePropertiesAggregationTypeToJSON(value['type']),
        'propertyName': value['propertyName'],
    };
}

