/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonAggregate } from '../models/CommonAggregate.js';
import { CommonFunction } from '../models/CommonFunction.js';
import { HttpFile } from '../http/http.js';

/**
* the query to fetch metrics data, promql
*/
export class CommonQuery {
    'query'?: string;
    'alias'?: string;
    'id'?: string;
    'labelSelector'?: { [key: string]: string; };
    'aggregate'?: CommonAggregate;
    'functions'?: Array<CommonFunction>;
    'color'?: string;
    'disabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "labelSelector",
            "baseName": "labelSelector",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "aggregate",
            "baseName": "aggregate",
            "type": "CommonAggregate",
            "format": ""
        },
        {
            "name": "functions",
            "baseName": "functions",
            "type": "Array<CommonFunction>",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonQuery.attributeTypeMap;
    }

    public constructor() {
    }
}
