/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonProjectSuperset } from '../models/CommonProjectSuperset.js';
import { CommonProjectType } from '../models/CommonProjectType.js';
import { CommonProjectVisibility } from '../models/CommonProjectVisibility.js';
import { HttpFile } from '../http/http.js';

export class CommonProjectInfo {
    'id'?: string;
    'displayName'?: string;
    'description'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'slug'?: string;
    'owner'?: string;
    'visibility'?: CommonProjectVisibility;
    'type'?: CommonProjectType;
    'multiVersion'?: boolean;
    'supersetEnable'?: boolean;
    'superset'?: CommonProjectSuperset;
    'enableDisk'?: boolean;
    'enableMaterializedView'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "slug",
            "baseName": "slug",
            "type": "string",
            "format": ""
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "string",
            "format": ""
        },
        {
            "name": "visibility",
            "baseName": "visibility",
            "type": "CommonProjectVisibility",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CommonProjectType",
            "format": ""
        },
        {
            "name": "multiVersion",
            "baseName": "multiVersion",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "supersetEnable",
            "baseName": "supersetEnable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "superset",
            "baseName": "superset",
            "type": "CommonProjectSuperset",
            "format": ""
        },
        {
            "name": "enableDisk",
            "baseName": "enableDisk",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "enableMaterializedView",
            "baseName": "enableMaterializedView",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonProjectInfo.attributeTypeMap;
    }

    public constructor() {
    }
}


