/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonCoinIDAddressIdentifier } from './CommonCoinIDAddressIdentifier.js';
import {
    CommonCoinIDAddressIdentifierFromJSON,
    CommonCoinIDAddressIdentifierFromJSONTyped,
    CommonCoinIDAddressIdentifierToJSON,
} from './CommonCoinIDAddressIdentifier.js';

/**
 * 
 * @export
 * @interface CommonCoinID
 */
export interface CommonCoinID {
    /**
     * 
     * @type {string}
     * @memberof CommonCoinID
     */
    symbol?: string;
    /**
     * 
     * @type {CommonCoinIDAddressIdentifier}
     * @memberof CommonCoinID
     */
    address?: CommonCoinIDAddressIdentifier;
}

/**
 * Check if a given object implements the CommonCoinID interface.
 */
export function instanceOfCommonCoinID(value: object): boolean {
    return true;
}

export function CommonCoinIDFromJSON(json: any): CommonCoinID {
    return CommonCoinIDFromJSONTyped(json, false);
}

export function CommonCoinIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonCoinID {
    if (json == null) {
        return json;
    }
    return {
        
        'symbol': json['symbol'] == null ? undefined : json['symbol'],
        'address': json['address'] == null ? undefined : CommonCoinIDAddressIdentifierFromJSON(json['address']),
    };
}

export function CommonCoinIDToJSON(value?: CommonCoinID | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'symbol': value['symbol'],
        'address': CommonCoinIDAddressIdentifierToJSON(value['address']),
    };
}

