/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonMatrixMetric } from '../models/CommonMatrixMetric.js';
import { CommonMatrixValue } from '../models/CommonMatrixValue.js';
import { HttpFile } from '../http/http.js';

export class CommonMatrixSample {
    'metric'?: CommonMatrixMetric;
    'values'?: Array<CommonMatrixValue>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "metric",
            "baseName": "metric",
            "type": "CommonMatrixMetric",
            "format": ""
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<CommonMatrixValue>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonMatrixSample.attributeTypeMap;
    }

    public constructor() {
    }
}
