/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CommonNotificationType = {
    General: 'GENERAL',
    ProcessorUploadFailed: 'PROCESSOR_UPLOAD_FAILED',
    ProcessorUploadSuccess: 'PROCESSOR_UPLOAD_SUCCESS',
    ProcessorObsoleted: 'PROCESSOR_OBSOLETED',
    ProcessorStopped: 'PROCESSOR_STOPPED',
    ProcessorActivated: 'PROCESSOR_ACTIVATED',
    ProcessorGeneral: 'PROCESSOR_GENERAL',
    ProcessorError: 'PROCESSOR_ERROR',
    ExportTaskFailed: 'EXPORT_TASK_FAILED',
    ExportTaskSuccess: 'EXPORT_TASK_SUCCESS',
    BillingInvoice: 'BILLING_INVOICE',
    BillingPayment: 'BILLING_PAYMENT',
    BillingSubscription: 'BILLING_SUBSCRIPTION'
} as const;
export type CommonNotificationType = typeof CommonNotificationType[keyof typeof CommonNotificationType];


export function instanceOfCommonNotificationType(value: any): boolean {
    return Object.values(CommonNotificationType).includes(value);
}

export function CommonNotificationTypeFromJSON(json: any): CommonNotificationType {
    return CommonNotificationTypeFromJSONTyped(json, false);
}

export function CommonNotificationTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonNotificationType {
    return json as CommonNotificationType;
}

export function CommonNotificationTypeToJSON(value?: CommonNotificationType | null): any {
    return value as any;
}

