/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonRetentionQueryFilterTimeFilter } from '../models/CommonRetentionQueryFilterTimeFilter.js';
import { CommonSelectorExpr } from '../models/CommonSelectorExpr.js';
import { HttpFile } from '../http/http.js';

export class CommonRetentionQueryFilter {
    'propertyFilter'?: CommonSelectorExpr;
    'timeFilter'?: CommonRetentionQueryFilterTimeFilter;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "propertyFilter",
            "baseName": "propertyFilter",
            "type": "CommonSelectorExpr",
            "format": ""
        },
        {
            "name": "timeFilter",
            "baseName": "timeFilter",
            "type": "CommonRetentionQueryFilterTimeFilter",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonRetentionQueryFilter.attributeTypeMap;
    }

    public constructor() {
    }
}
