/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CommonSegmentParameter
 */
export interface CommonSegmentParameter {
    /**
     * 
     * @type {string}
     * @memberof CommonSegmentParameter
     */
    cohortId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommonSegmentParameter
     */
    allUsers?: boolean;
}

/**
 * Check if a given object implements the CommonSegmentParameter interface.
 */
export function instanceOfCommonSegmentParameter(value: object): boolean {
    return true;
}

export function CommonSegmentParameterFromJSON(json: any): CommonSegmentParameter {
    return CommonSegmentParameterFromJSONTyped(json, false);
}

export function CommonSegmentParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSegmentParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'cohortId': json['cohortId'] == null ? undefined : json['cohortId'],
        'allUsers': json['allUsers'] == null ? undefined : json['allUsers'],
    };
}

export function CommonSegmentParameterToJSON(value?: CommonSegmentParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cohortId': value['cohortId'],
        'allUsers': value['allUsers'],
    };
}

