/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonCohortsGroup } from '../models/CommonCohortsGroup.js';
import { CommonJoinOperator } from '../models/CommonJoinOperator.js';
import { HttpFile } from '../http/http.js';

export class CommonCohortsQuery {
    'joinOperator'?: CommonJoinOperator;
    'groups'?: Array<CommonCohortsGroup>;
    'name'?: string;
    'id'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "joinOperator",
            "baseName": "joinOperator",
            "type": "CommonJoinOperator",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Array<CommonCohortsGroup>",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonCohortsQuery.attributeTypeMap;
    }

    public constructor() {
    }
}


