/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonCohortsFilterAggregationAggregatePropertiesAggregationType } from '../models/CommonCohortsFilterAggregationAggregatePropertiesAggregationType.js';
import { HttpFile } from '../http/http.js';

export class CommonCohortsFilterAggregationAggregateProperties {
    'type'?: CommonCohortsFilterAggregationAggregatePropertiesAggregationType;
    'propertyName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CommonCohortsFilterAggregationAggregatePropertiesAggregationType",
            "format": ""
        },
        {
            "name": "propertyName",
            "baseName": "propertyName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonCohortsFilterAggregationAggregateProperties.attributeTypeMap;
    }

    public constructor() {
    }
}


