/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CommonProjectSuperset
 */
export interface CommonProjectSuperset {
    /**
     * 
     * @type {string}
     * @memberof CommonProjectSuperset
     */
    projectId?: string;
    /**
     * 
     * @type {Date}
     * @memberof CommonProjectSuperset
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CommonProjectSuperset
     */
    syncAt?: Date;
}

/**
 * Check if a given object implements the CommonProjectSuperset interface.
 */
export function instanceOfCommonProjectSuperset(value: object): boolean {
    return true;
}

export function CommonProjectSupersetFromJSON(json: any): CommonProjectSuperset {
    return CommonProjectSupersetFromJSONTyped(json, false);
}

export function CommonProjectSupersetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonProjectSuperset {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'syncAt': json['syncAt'] == null ? undefined : (new Date(json['syncAt'])),
    };
}

export function CommonProjectSupersetToJSON(value?: CommonProjectSuperset | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'projectId': value['projectId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'syncAt': value['syncAt'] == null ? undefined : ((value['syncAt']).toISOString()),
    };
}

