/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonDuration } from '../models/CommonDuration.js';
import { CommonTimeRangeTimeLike } from '../models/CommonTimeRangeTimeLike.js';
import { HttpFile } from '../http/http.js';

export class CommonTimeRange {
    'start'?: CommonTimeRangeTimeLike;
    'end'?: CommonTimeRangeTimeLike;
    'step'?: string;
    'interval'?: CommonDuration;
    'timezone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "CommonTimeRangeTimeLike",
            "format": ""
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "CommonTimeRangeTimeLike",
            "format": ""
        },
        {
            "name": "step",
            "baseName": "step",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "CommonDuration",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonTimeRange.attributeTypeMap;
    }

    public constructor() {
    }
}
