/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The same to user but with sensitive data removed.
 * @export
 * @interface CommonUserInfo
 */
export interface CommonUserInfo {
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    picture?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonUserInfo
     */
    username?: string;
}

/**
 * Check if a given object implements the CommonUserInfo interface.
 */
export function instanceOfCommonUserInfo(value: object): boolean {
    return true;
}

export function CommonUserInfoFromJSON(json: any): CommonUserInfo {
    return CommonUserInfoFromJSONTyped(json, false);
}

export function CommonUserInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonUserInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'picture': json['picture'] == null ? undefined : json['picture'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function CommonUserInfoToJSON(value?: CommonUserInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'lastName': value['lastName'],
        'firstName': value['firstName'],
        'nickname': value['nickname'],
        'picture': value['picture'],
        'username': value['username'],
    };
}

