/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonArgument } from '../models/CommonArgument.js';
import { HttpFile } from '../http/http.js';

export class CommonFunction {
    'name'?: string;
    'arguments'?: Array<CommonArgument>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "arguments",
            "baseName": "arguments",
            "type": "Array<CommonArgument>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonFunction.attributeTypeMap;
    }

    public constructor() {
    }
}
