/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export enum CommonCohortsFilterAggregationOperatorType {
    Eq = 'EQ',
    Neq = 'NEQ',
    Gt = 'GT',
    Gte = 'GTE',
    Lt = 'LT',
    Lte = 'LTE',
    Between = 'BETWEEN',
    NotBetween = 'NOT_BETWEEN'
}
