/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonUserInfo } from './CommonUserInfo';
import {
    CommonUserInfoFromJSON,
    CommonUserInfoFromJSONTyped,
    CommonUserInfoToJSON,
} from './CommonUserInfo';

/**
 * 
 * @export
 * @interface CommonProjectProjectMember
 */
export interface CommonProjectProjectMember {
    /**
     * 
     * @type {CommonUserInfo}
     * @memberof CommonProjectProjectMember
     */
    user?: CommonUserInfo;
    /**
     * 
     * @type {string}
     * @memberof CommonProjectProjectMember
     */
    role?: string;
}

/**
 * Check if a given object implements the CommonProjectProjectMember interface.
 */
export function instanceOfCommonProjectProjectMember(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommonProjectProjectMemberFromJSON(json: any): CommonProjectProjectMember {
    return CommonProjectProjectMemberFromJSONTyped(json, false);
}

export function CommonProjectProjectMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonProjectProjectMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : CommonUserInfoFromJSON(json['user']),
        'role': !exists(json, 'role') ? undefined : json['role'],
    };
}

export function CommonProjectProjectMemberToJSON(value?: CommonProjectProjectMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': CommonUserInfoToJSON(value.user),
        'role': value.role,
    };
}

