/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonRetentionMatrixSample } from './CommonRetentionMatrixSample';
import {
    CommonRetentionMatrixSampleFromJSON,
    CommonRetentionMatrixSampleFromJSONTyped,
    CommonRetentionMatrixSampleToJSON,
} from './CommonRetentionMatrixSample';

/**
 * 
 * @export
 * @interface CommonRetentionMatrix
 */
export interface CommonRetentionMatrix {
    /**
     * 
     * @type {Array<CommonRetentionMatrixSample>}
     * @memberof CommonRetentionMatrix
     */
    samples?: Array<CommonRetentionMatrixSample>;
}

/**
 * Check if a given object implements the CommonRetentionMatrix interface.
 */
export function instanceOfCommonRetentionMatrix(value: object): boolean {
    return true;
}

export function CommonRetentionMatrixFromJSON(json: any): CommonRetentionMatrix {
    return CommonRetentionMatrixFromJSONTyped(json, false);
}

export function CommonRetentionMatrixFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonRetentionMatrix {
    if (json == null) {
        return json;
    }
    return {
        
        'samples': json['samples'] == null ? undefined : ((json['samples'] as Array<any>).map(CommonRetentionMatrixSampleFromJSON)),
    };
}

export function CommonRetentionMatrixToJSON(value?: CommonRetentionMatrix | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'samples': value['samples'] == null ? undefined : ((value['samples'] as Array<any>).map(CommonRetentionMatrixSampleToJSON)),
    };
}

