/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonOrganizationRole } from '../models/CommonOrganizationRole.js';
import { CommonUserInfo } from '../models/CommonUserInfo.js';
import { HttpFile } from '../http/http.js';

export class CommonOrganizationMember {
    'user'?: CommonUserInfo;
    'role'?: CommonOrganizationRole;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "user",
            "baseName": "user",
            "type": "CommonUserInfo",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "CommonOrganizationRole",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonOrganizationMember.attributeTypeMap;
    }

    public constructor() {
    }
}


