/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface CommonCoinIDAddressIdentifier
 */
export interface CommonCoinIDAddressIdentifier {
    /**
     * 
     * @type {string}
     * @memberof CommonCoinIDAddressIdentifier
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonCoinIDAddressIdentifier
     */
    chain?: string;
}

/**
 * Check if a given object implements the CommonCoinIDAddressIdentifier interface.
 */
export function instanceOfCommonCoinIDAddressIdentifier(value: object): value is CommonCoinIDAddressIdentifier {
    return true;
}

export function CommonCoinIDAddressIdentifierFromJSON(json: any): CommonCoinIDAddressIdentifier {
    return CommonCoinIDAddressIdentifierFromJSONTyped(json, false);
}

export function CommonCoinIDAddressIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonCoinIDAddressIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'chain': json['chain'] == null ? undefined : json['chain'],
    };
}

  export function CommonCoinIDAddressIdentifierToJSON(json: any): CommonCoinIDAddressIdentifier {
      return CommonCoinIDAddressIdentifierToJSONTyped(json, false);
  }

  export function CommonCoinIDAddressIdentifierToJSONTyped(value?: CommonCoinIDAddressIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'address': value['address'],
        'chain': value['chain'],
    };
}

