/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonDuration } from './CommonDuration.js';
import {
    CommonDurationFromJSON,
    CommonDurationFromJSONTyped,
    CommonDurationToJSON,
    CommonDurationToJSONTyped,
} from './CommonDuration.js';

/**
 * 
 * @export
 * @interface CommonSegmentationQueryAggregationCountUnique
 */
export interface CommonSegmentationQueryAggregationCountUnique {
    /**
     * 
     * @type {CommonDuration}
     * @memberof CommonSegmentationQueryAggregationCountUnique
     */
    duration?: CommonDuration;
}

/**
 * Check if a given object implements the CommonSegmentationQueryAggregationCountUnique interface.
 */
export function instanceOfCommonSegmentationQueryAggregationCountUnique(value: object): value is CommonSegmentationQueryAggregationCountUnique {
    return true;
}

export function CommonSegmentationQueryAggregationCountUniqueFromJSON(json: any): CommonSegmentationQueryAggregationCountUnique {
    return CommonSegmentationQueryAggregationCountUniqueFromJSONTyped(json, false);
}

export function CommonSegmentationQueryAggregationCountUniqueFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSegmentationQueryAggregationCountUnique {
    if (json == null) {
        return json;
    }
    return {
        
        'duration': json['duration'] == null ? undefined : CommonDurationFromJSON(json['duration']),
    };
}

  export function CommonSegmentationQueryAggregationCountUniqueToJSON(json: any): CommonSegmentationQueryAggregationCountUnique {
      return CommonSegmentationQueryAggregationCountUniqueToJSONTyped(json, false);
  }

  export function CommonSegmentationQueryAggregationCountUniqueToJSONTyped(value?: CommonSegmentationQueryAggregationCountUnique | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration': CommonDurationToJSON(value['duration']),
    };
}

