/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonAny } from './CommonAny.js';
import {
    CommonAnyFromJSON,
    CommonAnyFromJSONTyped,
    CommonAnyToJSON,
    CommonAnyToJSONTyped,
} from './CommonAny.js';
import type { CommonCohortsFilterAggregationAggregateProperties } from './CommonCohortsFilterAggregationAggregateProperties.js';
import {
    CommonCohortsFilterAggregationAggregatePropertiesFromJSON,
    CommonCohortsFilterAggregationAggregatePropertiesFromJSONTyped,
    CommonCohortsFilterAggregationAggregatePropertiesToJSON,
    CommonCohortsFilterAggregationAggregatePropertiesToJSONTyped,
} from './CommonCohortsFilterAggregationAggregateProperties.js';
import type { CommonCohortsFilterAggregationOperatorType } from './CommonCohortsFilterAggregationOperatorType.js';
import {
    CommonCohortsFilterAggregationOperatorTypeFromJSON,
    CommonCohortsFilterAggregationOperatorTypeFromJSONTyped,
    CommonCohortsFilterAggregationOperatorTypeToJSON,
    CommonCohortsFilterAggregationOperatorTypeToJSONTyped,
} from './CommonCohortsFilterAggregationOperatorType.js';

/**
 * 
 * @export
 * @interface CommonCohortsFilterAggregation
 */
export interface CommonCohortsFilterAggregation {
    /**
     * 
     * @type {object}
     * @memberof CommonCohortsFilterAggregation
     */
    total?: object;
    /**
     * 
     * @type {CommonCohortsFilterAggregationAggregateProperties}
     * @memberof CommonCohortsFilterAggregation
     */
    aggregateProperties?: CommonCohortsFilterAggregationAggregateProperties;
    /**
     * 
     * @type {CommonCohortsFilterAggregationOperatorType}
     * @memberof CommonCohortsFilterAggregation
     */
    operator?: CommonCohortsFilterAggregationOperatorType;
    /**
     * 
     * @type {Array<CommonAny>}
     * @memberof CommonCohortsFilterAggregation
     */
    value?: Array<CommonAny>;
}



/**
 * Check if a given object implements the CommonCohortsFilterAggregation interface.
 */
export function instanceOfCommonCohortsFilterAggregation(value: object): value is CommonCohortsFilterAggregation {
    return true;
}

export function CommonCohortsFilterAggregationFromJSON(json: any): CommonCohortsFilterAggregation {
    return CommonCohortsFilterAggregationFromJSONTyped(json, false);
}

export function CommonCohortsFilterAggregationFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonCohortsFilterAggregation {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'aggregateProperties': json['aggregateProperties'] == null ? undefined : CommonCohortsFilterAggregationAggregatePropertiesFromJSON(json['aggregateProperties']),
        'operator': json['operator'] == null ? undefined : CommonCohortsFilterAggregationOperatorTypeFromJSON(json['operator']),
        'value': json['value'] == null ? undefined : ((json['value'] as Array<any>).map(CommonAnyFromJSON)),
    };
}

  export function CommonCohortsFilterAggregationToJSON(json: any): CommonCohortsFilterAggregation {
      return CommonCohortsFilterAggregationToJSONTyped(json, false);
  }

  export function CommonCohortsFilterAggregationToJSONTyped(value?: CommonCohortsFilterAggregation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'aggregateProperties': CommonCohortsFilterAggregationAggregatePropertiesToJSON(value['aggregateProperties']),
        'operator': CommonCohortsFilterAggregationOperatorTypeToJSON(value['operator']),
        'value': value['value'] == null ? undefined : ((value['value'] as Array<any>).map(CommonAnyToJSON)),
    };
}

