/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonSegmentationQueryAggregationAggregateProperties } from '../models/CommonSegmentationQueryAggregationAggregateProperties.js';
import { CommonSegmentationQueryAggregationCountUnique } from '../models/CommonSegmentationQueryAggregationCountUnique.js';
import { HttpFile } from '../http/http.js';

export class CommonSegmentationQueryAggregation {
    'total'?: any;
    'unique'?: any;
    'countUnique'?: CommonSegmentationQueryAggregationCountUnique;
    'aggregateProperties'?: CommonSegmentationQueryAggregationAggregateProperties;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "total",
            "baseName": "total",
            "type": "any",
            "format": ""
        },
        {
            "name": "unique",
            "baseName": "unique",
            "type": "any",
            "format": ""
        },
        {
            "name": "countUnique",
            "baseName": "countUnique",
            "type": "CommonSegmentationQueryAggregationCountUnique",
            "format": ""
        },
        {
            "name": "aggregateProperties",
            "baseName": "aggregateProperties",
            "type": "CommonSegmentationQueryAggregationAggregateProperties",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonSegmentationQueryAggregation.attributeTypeMap;
    }

    public constructor() {
    }
}
