/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonBigInteger } from './CommonBigInteger.js';
import {
    CommonBigIntegerFromJSON,
    CommonBigIntegerFromJSONTyped,
    CommonBigIntegerToJSON,
    CommonBigIntegerToJSONTyped,
} from './CommonBigInteger.js';

/**
 * 
 * @export
 * @interface CommonBigDecimal
 */
export interface CommonBigDecimal {
    /**
     * 
     * @type {CommonBigInteger}
     * @memberof CommonBigDecimal
     */
    value?: CommonBigInteger;
    /**
     * 
     * @type {number}
     * @memberof CommonBigDecimal
     */
    exp?: number;
}

/**
 * Check if a given object implements the CommonBigDecimal interface.
 */
export function instanceOfCommonBigDecimal(value: object): value is CommonBigDecimal {
    return true;
}

export function CommonBigDecimalFromJSON(json: any): CommonBigDecimal {
    return CommonBigDecimalFromJSONTyped(json, false);
}

export function CommonBigDecimalFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonBigDecimal {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : CommonBigIntegerFromJSON(json['value']),
        'exp': json['exp'] == null ? undefined : json['exp'],
    };
}

  export function CommonBigDecimalToJSON(json: any): CommonBigDecimal {
      return CommonBigDecimalToJSONTyped(json, false);
  }

  export function CommonBigDecimalToJSONTyped(value?: CommonBigDecimal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': CommonBigIntegerToJSON(value['value']),
        'exp': value['exp'],
    };
}

