/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonOrganization } from './CommonOrganization';
import {
    CommonOrganizationFromJSON,
    CommonOrganizationFromJSONTyped,
    CommonOrganizationToJSON,
} from './CommonOrganization';
import type { CommonTier } from './CommonTier';
import {
    CommonTierFromJSON,
    CommonTierFromJSONTyped,
    CommonTierToJSON,
} from './CommonTier';
import type { CommonUser } from './CommonUser';
import {
    CommonUserFromJSON,
    CommonUserFromJSONTyped,
    CommonUserToJSON,
} from './CommonUser';

/**
 * 
 * @export
 * @interface CommonOwner
 */
export interface CommonOwner {
    /**
     * 
     * @type {CommonUser}
     * @memberof CommonOwner
     */
    user?: CommonUser;
    /**
     * 
     * @type {CommonOrganization}
     * @memberof CommonOwner
     */
    organization?: CommonOrganization;
    /**
     * 
     * @type {CommonTier}
     * @memberof CommonOwner
     */
    tier?: CommonTier;
}

/**
 * Check if a given object implements the CommonOwner interface.
 */
export function instanceOfCommonOwner(value: object): boolean {
    return true;
}

export function CommonOwnerFromJSON(json: any): CommonOwner {
    return CommonOwnerFromJSONTyped(json, false);
}

export function CommonOwnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonOwner {
    if (json == null) {
        return json;
    }
    return {
        
        'user': json['user'] == null ? undefined : CommonUserFromJSON(json['user']),
        'organization': json['organization'] == null ? undefined : CommonOrganizationFromJSON(json['organization']),
        'tier': json['tier'] == null ? undefined : CommonTierFromJSON(json['tier']),
    };
}

export function CommonOwnerToJSON(value?: CommonOwner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'user': CommonUserToJSON(value['user']),
        'organization': CommonOrganizationToJSON(value['organization']),
        'tier': CommonTierToJSON(value['tier']),
    };
}

