/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonSelectorExpr } from '../models/CommonSelectorExpr.js';
import { CommonSystemSQLQueryAggregation } from '../models/CommonSystemSQLQueryAggregation.js';
import { HttpFile } from '../http/http.js';

export class CommonSystemSQLQuery {
    'id'?: string;
    'alias'?: string;
    'name'?: string;
    'tableName'?: string;
    'aggregation'?: CommonSystemSQLQueryAggregation;
    'selectorExpr'?: CommonSelectorExpr;
    'groupBy'?: Array<string>;
    'disabled'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "alias",
            "baseName": "alias",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tableName",
            "baseName": "tableName",
            "type": "string",
            "format": ""
        },
        {
            "name": "aggregation",
            "baseName": "aggregation",
            "type": "CommonSystemSQLQueryAggregation",
            "format": ""
        },
        {
            "name": "selectorExpr",
            "baseName": "selectorExpr",
            "type": "CommonSelectorExpr",
            "format": ""
        },
        {
            "name": "groupBy",
            "baseName": "groupBy",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonSystemSQLQuery.attributeTypeMap;
    }

    public constructor() {
    }
}
