/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonOrganizationRole } from './CommonOrganizationRole';
import {
    CommonOrganizationRoleFromJSON,
    CommonOrganizationRoleFromJSONTyped,
    CommonOrganizationRoleToJSON,
} from './CommonOrganizationRole';
import type { CommonUserInfo } from './CommonUserInfo';
import {
    CommonUserInfoFromJSON,
    CommonUserInfoFromJSONTyped,
    CommonUserInfoToJSON,
} from './CommonUserInfo';

/**
 * 
 * @export
 * @interface CommonOrganizationMember
 */
export interface CommonOrganizationMember {
    /**
     * 
     * @type {CommonUserInfo}
     * @memberof CommonOrganizationMember
     */
    user?: CommonUserInfo;
    /**
     * 
     * @type {CommonOrganizationRole}
     * @memberof CommonOrganizationMember
     */
    role?: CommonOrganizationRole;
}

/**
 * Check if a given object implements the CommonOrganizationMember interface.
 */
export function instanceOfCommonOrganizationMember(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommonOrganizationMemberFromJSON(json: any): CommonOrganizationMember {
    return CommonOrganizationMemberFromJSONTyped(json, false);
}

export function CommonOrganizationMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonOrganizationMember {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : CommonUserInfoFromJSON(json['user']),
        'role': !exists(json, 'role') ? undefined : CommonOrganizationRoleFromJSON(json['role']),
    };
}

export function CommonOrganizationMemberToJSON(value?: CommonOrganizationMember | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': CommonUserInfoToJSON(value.user),
        'role': CommonOrganizationRoleToJSON(value.role),
    };
}

