/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonSegmentationQueryAggregationAggregatePropertiesAggregationType } from './CommonSegmentationQueryAggregationAggregatePropertiesAggregationType';
import {
    CommonSegmentationQueryAggregationAggregatePropertiesAggregationTypeFromJSON,
    CommonSegmentationQueryAggregationAggregatePropertiesAggregationTypeFromJSONTyped,
    CommonSegmentationQueryAggregationAggregatePropertiesAggregationTypeToJSON,
} from './CommonSegmentationQueryAggregationAggregatePropertiesAggregationType';

/**
 * 
 * @export
 * @interface CommonSegmentationQueryAggregationAggregateProperties
 */
export interface CommonSegmentationQueryAggregationAggregateProperties {
    /**
     * 
     * @type {CommonSegmentationQueryAggregationAggregatePropertiesAggregationType}
     * @memberof CommonSegmentationQueryAggregationAggregateProperties
     */
    type?: CommonSegmentationQueryAggregationAggregatePropertiesAggregationType;
    /**
     * 
     * @type {string}
     * @memberof CommonSegmentationQueryAggregationAggregateProperties
     */
    propertyName?: string;
}

/**
 * Check if a given object implements the CommonSegmentationQueryAggregationAggregateProperties interface.
 */
export function instanceOfCommonSegmentationQueryAggregationAggregateProperties(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CommonSegmentationQueryAggregationAggregatePropertiesFromJSON(json: any): CommonSegmentationQueryAggregationAggregateProperties {
    return CommonSegmentationQueryAggregationAggregatePropertiesFromJSONTyped(json, false);
}

export function CommonSegmentationQueryAggregationAggregatePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonSegmentationQueryAggregationAggregateProperties {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : CommonSegmentationQueryAggregationAggregatePropertiesAggregationTypeFromJSON(json['type']),
        'propertyName': !exists(json, 'propertyName') ? undefined : json['propertyName'],
    };
}

export function CommonSegmentationQueryAggregationAggregatePropertiesToJSON(value?: CommonSegmentationQueryAggregationAggregateProperties | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': CommonSegmentationQueryAggregationAggregatePropertiesAggregationTypeToJSON(value.type),
        'propertyName': value.propertyName,
    };
}

