/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonRetentionQueryFilter } from './CommonRetentionQueryFilter.js';
import {
    CommonRetentionQueryFilterFromJSON,
    CommonRetentionQueryFilterFromJSONTyped,
    CommonRetentionQueryFilterToJSON,
} from './CommonRetentionQueryFilter.js';

/**
 * 
 * @export
 * @interface CommonRetentionQueryResource
 */
export interface CommonRetentionQueryResource {
    /**
     * 
     * @type {Array<string>}
     * @memberof CommonRetentionQueryResource
     */
    eventNames?: Array<string>;
    /**
     * 
     * @type {CommonRetentionQueryFilter}
     * @memberof CommonRetentionQueryResource
     */
    filter?: CommonRetentionQueryFilter;
}

/**
 * Check if a given object implements the CommonRetentionQueryResource interface.
 */
export function instanceOfCommonRetentionQueryResource(value: object): boolean {
    return true;
}

export function CommonRetentionQueryResourceFromJSON(json: any): CommonRetentionQueryResource {
    return CommonRetentionQueryResourceFromJSONTyped(json, false);
}

export function CommonRetentionQueryResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonRetentionQueryResource {
    if (json == null) {
        return json;
    }
    return {
        
        'eventNames': json['eventNames'] == null ? undefined : json['eventNames'],
        'filter': json['filter'] == null ? undefined : CommonRetentionQueryFilterFromJSON(json['filter']),
    };
}

export function CommonRetentionQueryResourceToJSON(value?: CommonRetentionQueryResource | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'eventNames': value['eventNames'],
        'filter': CommonRetentionQueryFilterToJSON(value['filter']),
    };
}

