/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonSegmentationQueryAggregationAggregatePropertiesAggregationType } from '../models/CommonSegmentationQueryAggregationAggregatePropertiesAggregationType.js';
import { HttpFile } from '../http/http.js';

export class CommonSegmentationQueryAggregationAggregateProperties {
    'type'?: CommonSegmentationQueryAggregationAggregatePropertiesAggregationType;
    'propertyName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CommonSegmentationQueryAggregationAggregatePropertiesAggregationType",
            "format": ""
        },
        {
            "name": "propertyName",
            "baseName": "propertyName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CommonSegmentationQueryAggregationAggregateProperties.attributeTypeMap;
    }

    public constructor() {
    }
}


