/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonCoinID } from './CommonCoinID.js';
import {
    CommonCoinIDFromJSON,
    CommonCoinIDFromJSONTyped,
    CommonCoinIDToJSON,
    CommonCoinIDToJSONTyped,
} from './CommonCoinID.js';
import type { CommonComputeStats } from './CommonComputeStats.js';
import {
    CommonComputeStatsFromJSON,
    CommonComputeStatsFromJSONTyped,
    CommonComputeStatsToJSON,
    CommonComputeStatsToJSONTyped,
} from './CommonComputeStats.js';

/**
 * 
 * @export
 * @interface InsightsServiceListCoinsResponse
 */
export interface InsightsServiceListCoinsResponse {
    /**
     * 
     * @type {Array<CommonCoinID>}
     * @memberof InsightsServiceListCoinsResponse
     */
    coins?: Array<CommonCoinID>;
    /**
     * 
     * @type {CommonComputeStats}
     * @memberof InsightsServiceListCoinsResponse
     */
    computeStats?: CommonComputeStats;
}

/**
 * Check if a given object implements the InsightsServiceListCoinsResponse interface.
 */
export function instanceOfInsightsServiceListCoinsResponse(value: object): value is InsightsServiceListCoinsResponse {
    return true;
}

export function InsightsServiceListCoinsResponseFromJSON(json: any): InsightsServiceListCoinsResponse {
    return InsightsServiceListCoinsResponseFromJSONTyped(json, false);
}

export function InsightsServiceListCoinsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightsServiceListCoinsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'coins': json['coins'] == null ? undefined : ((json['coins'] as Array<any>).map(CommonCoinIDFromJSON)),
        'computeStats': json['computeStats'] == null ? undefined : CommonComputeStatsFromJSON(json['computeStats']),
    };
}

  export function InsightsServiceListCoinsResponseToJSON(json: any): InsightsServiceListCoinsResponse {
      return InsightsServiceListCoinsResponseToJSONTyped(json, false);
  }

  export function InsightsServiceListCoinsResponseToJSONTyped(value?: InsightsServiceListCoinsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coins': value['coins'] == null ? undefined : ((value['coins'] as Array<any>).map(CommonCoinIDToJSON)),
        'computeStats': CommonComputeStatsToJSON(value['computeStats']),
    };
}

