/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { InsightsServiceQueryResponseResult } from './InsightsServiceQueryResponseResult.js';
import {
    InsightsServiceQueryResponseResultFromJSON,
    InsightsServiceQueryResponseResultFromJSONTyped,
    InsightsServiceQueryResponseResultToJSON,
    InsightsServiceQueryResponseResultToJSONTyped,
} from './InsightsServiceQueryResponseResult.js';

/**
 * 
 * @export
 * @interface InsightsServiceQueryResponse
 */
export interface InsightsServiceQueryResponse {
    /**
     * 
     * @type {Array<InsightsServiceQueryResponseResult>}
     * @memberof InsightsServiceQueryResponse
     */
    results?: Array<InsightsServiceQueryResponseResult>;
}

/**
 * Check if a given object implements the InsightsServiceQueryResponse interface.
 */
export function instanceOfInsightsServiceQueryResponse(value: object): value is InsightsServiceQueryResponse {
    return true;
}

export function InsightsServiceQueryResponseFromJSON(json: any): InsightsServiceQueryResponse {
    return InsightsServiceQueryResponseFromJSONTyped(json, false);
}

export function InsightsServiceQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightsServiceQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(InsightsServiceQueryResponseResultFromJSON)),
    };
}

  export function InsightsServiceQueryResponseToJSON(json: any): InsightsServiceQueryResponse {
      return InsightsServiceQueryResponseToJSONTyped(json, false);
  }

  export function InsightsServiceQueryResponseToJSONTyped(value?: InsightsServiceQueryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(InsightsServiceQueryResponseResultToJSON)),
    };
}

