/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonPriceSegmentationQuery } from './CommonPriceSegmentationQuery';
import {
    CommonPriceSegmentationQueryFromJSON,
    CommonPriceSegmentationQueryFromJSONTyped,
    CommonPriceSegmentationQueryToJSON,
} from './CommonPriceSegmentationQuery';
import type { CommonQuery } from './CommonQuery';
import {
    CommonQueryFromJSON,
    CommonQueryFromJSONTyped,
    CommonQueryToJSON,
} from './CommonQuery';
import type { CommonSegmentationQuery } from './CommonSegmentationQuery';
import {
    CommonSegmentationQueryFromJSON,
    CommonSegmentationQueryFromJSONTyped,
    CommonSegmentationQueryToJSON,
} from './CommonSegmentationQuery';
import type { InsightsServiceDataSource } from './InsightsServiceDataSource';
import {
    InsightsServiceDataSourceFromJSON,
    InsightsServiceDataSourceFromJSONTyped,
    InsightsServiceDataSourceToJSON,
} from './InsightsServiceDataSource';

/**
 * 
 * @export
 * @interface InsightsServiceQueryRequestQuery
 */
export interface InsightsServiceQueryRequestQuery {
    /**
     * 
     * @type {CommonQuery}
     * @memberof InsightsServiceQueryRequestQuery
     */
    metricsQuery?: CommonQuery;
    /**
     * 
     * @type {CommonSegmentationQuery}
     * @memberof InsightsServiceQueryRequestQuery
     */
    eventsQuery?: CommonSegmentationQuery;
    /**
     * 
     * @type {CommonPriceSegmentationQuery}
     * @memberof InsightsServiceQueryRequestQuery
     */
    priceQuery?: CommonPriceSegmentationQuery;
    /**
     * 
     * @type {InsightsServiceDataSource}
     * @memberof InsightsServiceQueryRequestQuery
     */
    dataSource?: InsightsServiceDataSource;
    /**
     * 
     * @type {string}
     * @memberof InsightsServiceQueryRequestQuery
     */
    sourceName?: string;
}

/**
 * Check if a given object implements the InsightsServiceQueryRequestQuery interface.
 */
export function instanceOfInsightsServiceQueryRequestQuery(value: object): boolean {
    return true;
}

export function InsightsServiceQueryRequestQueryFromJSON(json: any): InsightsServiceQueryRequestQuery {
    return InsightsServiceQueryRequestQueryFromJSONTyped(json, false);
}

export function InsightsServiceQueryRequestQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): InsightsServiceQueryRequestQuery {
    if (json == null) {
        return json;
    }
    return {
        
        'metricsQuery': json['metricsQuery'] == null ? undefined : CommonQueryFromJSON(json['metricsQuery']),
        'eventsQuery': json['eventsQuery'] == null ? undefined : CommonSegmentationQueryFromJSON(json['eventsQuery']),
        'priceQuery': json['priceQuery'] == null ? undefined : CommonPriceSegmentationQueryFromJSON(json['priceQuery']),
        'dataSource': json['dataSource'] == null ? undefined : InsightsServiceDataSourceFromJSON(json['dataSource']),
        'sourceName': json['sourceName'] == null ? undefined : json['sourceName'],
    };
}

export function InsightsServiceQueryRequestQueryToJSON(value?: InsightsServiceQueryRequestQuery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metricsQuery': CommonQueryToJSON(value['metricsQuery']),
        'eventsQuery': CommonSegmentationQueryToJSON(value['eventsQuery']),
        'priceQuery': CommonPriceSegmentationQueryToJSON(value['priceQuery']),
        'dataSource': InsightsServiceDataSourceToJSON(value['dataSource']),
        'sourceName': value['sourceName'],
    };
}

