/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonRetentionQuery } from '../models/CommonRetentionQuery.js';
import { CommonTimeRangeLite } from '../models/CommonTimeRangeLite.js';
import { HttpFile } from '../http/http.js';

export class InsightsServiceInsightsServiceRetentionBody {
    'projectId'?: string;
    'version'?: number;
    'timeRange'?: CommonTimeRangeLite;
    'query'?: CommonRetentionQuery;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timeRange",
            "baseName": "timeRange",
            "type": "CommonTimeRangeLite",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "CommonRetentionQuery",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InsightsServiceInsightsServiceRetentionBody.attributeTypeMap;
    }

    public constructor() {
    }
}
