/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetricsServiceMetricsQueryResponseMatrix } from './MetricsServiceMetricsQueryResponseMatrix';
import {
    MetricsServiceMetricsQueryResponseMatrixFromJSON,
    MetricsServiceMetricsQueryResponseMatrixFromJSONTyped,
    MetricsServiceMetricsQueryResponseMatrixToJSON,
} from './MetricsServiceMetricsQueryResponseMatrix';

/**
 * 
 * @export
 * @interface MetricsServiceMetricsQueryResponseResult
 */
export interface MetricsServiceMetricsQueryResponseResult {
    /**
     * 
     * @type {MetricsServiceMetricsQueryResponseMatrix}
     * @memberof MetricsServiceMetricsQueryResponseResult
     */
    matrix?: MetricsServiceMetricsQueryResponseMatrix;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricsQueryResponseResult
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricsQueryResponseResult
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricsQueryResponseResult
     */
    id?: string;
}

/**
 * Check if a given object implements the MetricsServiceMetricsQueryResponseResult interface.
 */
export function instanceOfMetricsServiceMetricsQueryResponseResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetricsServiceMetricsQueryResponseResultFromJSON(json: any): MetricsServiceMetricsQueryResponseResult {
    return MetricsServiceMetricsQueryResponseResultFromJSONTyped(json, false);
}

export function MetricsServiceMetricsQueryResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceMetricsQueryResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'matrix': !exists(json, 'matrix') ? undefined : MetricsServiceMetricsQueryResponseMatrixFromJSON(json['matrix']),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function MetricsServiceMetricsQueryResponseResultToJSON(value?: MetricsServiceMetricsQueryResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'matrix': MetricsServiceMetricsQueryResponseMatrixToJSON(value.matrix),
        'error': value.error,
        'alias': value.alias,
        'id': value.id,
    };
}

