/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsServiceMetricMetadata
 */
export interface MetricsServiceMetricMetadata {
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricMetadata
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricMetadata
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricMetadata
     */
    help?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricMetadata
     */
    lastSeen?: string;
}

/**
 * Check if a given object implements the MetricsServiceMetricMetadata interface.
 */
export function instanceOfMetricsServiceMetricMetadata(value: object): boolean {
    return true;
}

export function MetricsServiceMetricMetadataFromJSON(json: any): MetricsServiceMetricMetadata {
    return MetricsServiceMetricMetadataFromJSONTyped(json, false);
}

export function MetricsServiceMetricMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceMetricMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'help': json['help'] == null ? undefined : json['help'],
        'lastSeen': json['lastSeen'] == null ? undefined : json['lastSeen'],
    };
}

export function MetricsServiceMetricMetadataToJSON(value?: MetricsServiceMetricMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'unit': value['unit'],
        'help': value['help'],
        'lastSeen': value['lastSeen'],
    };
}

