/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { MetricsServiceMetricsQueryResponseSample } from './MetricsServiceMetricsQueryResponseSample.js';
import {
    MetricsServiceMetricsQueryResponseSampleFromJSON,
    MetricsServiceMetricsQueryResponseSampleFromJSONTyped,
    MetricsServiceMetricsQueryResponseSampleToJSON,
    MetricsServiceMetricsQueryResponseSampleToJSONTyped,
} from './MetricsServiceMetricsQueryResponseSample.js';

/**
 * 
 * @export
 * @interface MetricsServiceQueryValueResponseResult
 */
export interface MetricsServiceQueryValueResponseResult {
    /**
     * 
     * @type {Array<MetricsServiceMetricsQueryResponseSample>}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    sample?: Array<MetricsServiceMetricsQueryResponseSample>;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    id?: string;
}

/**
 * Check if a given object implements the MetricsServiceQueryValueResponseResult interface.
 */
export function instanceOfMetricsServiceQueryValueResponseResult(value: object): value is MetricsServiceQueryValueResponseResult {
    return true;
}

export function MetricsServiceQueryValueResponseResultFromJSON(json: any): MetricsServiceQueryValueResponseResult {
    return MetricsServiceQueryValueResponseResultFromJSONTyped(json, false);
}

export function MetricsServiceQueryValueResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceQueryValueResponseResult {
    if (json == null) {
        return json;
    }
    return {
        
        'sample': json['sample'] == null ? undefined : ((json['sample'] as Array<any>).map(MetricsServiceMetricsQueryResponseSampleFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
        'alias': json['alias'] == null ? undefined : json['alias'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

  export function MetricsServiceQueryValueResponseResultToJSON(json: any): MetricsServiceQueryValueResponseResult {
      return MetricsServiceQueryValueResponseResultToJSONTyped(json, false);
  }

  export function MetricsServiceQueryValueResponseResultToJSONTyped(value?: MetricsServiceQueryValueResponseResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sample': value['sample'] == null ? undefined : ((value['sample'] as Array<any>).map(MetricsServiceMetricsQueryResponseSampleToJSON)),
        'error': value['error'],
        'alias': value['alias'],
        'id': value['id'],
    };
}

