/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { CommonQuery } from './CommonQuery.js';
import {
    CommonQueryFromJSON,
    CommonQueryFromJSONTyped,
    CommonQueryToJSON,
    CommonQueryToJSONTyped,
} from './CommonQuery.js';
import type { CommonFormula } from './CommonFormula.js';
import {
    CommonFormulaFromJSON,
    CommonFormulaFromJSONTyped,
    CommonFormulaToJSON,
    CommonFormulaToJSONTyped,
} from './CommonFormula.js';
import type { CommonTimeRangeLite } from './CommonTimeRangeLite.js';
import {
    CommonTimeRangeLiteFromJSON,
    CommonTimeRangeLiteFromJSONTyped,
    CommonTimeRangeLiteToJSON,
    CommonTimeRangeLiteToJSONTyped,
} from './CommonTimeRangeLite.js';

/**
 * 
 * @export
 * @interface MetricsServiceObservabilityServiceQueryRangeBody
 */
export interface MetricsServiceObservabilityServiceQueryRangeBody {
    /**
     * 
     * @type {Array<CommonQuery>}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    queries?: Array<CommonQuery>;
    /**
     * 
     * @type {Array<CommonFormula>}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    formulas?: Array<CommonFormula>;
    /**
     * 
     * @type {number}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    samplesLimit?: number;
    /**
     * 
     * @type {CommonTimeRangeLite}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    timeRange: CommonTimeRangeLite;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    projectId?: string;
    /**
     * 
     * @type {number}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    version?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricsServiceObservabilityServiceQueryRangeBody
     */
    samplesOffset?: number;
}

/**
 * Check if a given object implements the MetricsServiceObservabilityServiceQueryRangeBody interface.
 */
export function instanceOfMetricsServiceObservabilityServiceQueryRangeBody(value: object): value is MetricsServiceObservabilityServiceQueryRangeBody {
    if (!('timeRange' in value) || value['timeRange'] === undefined) return false;
    return true;
}

export function MetricsServiceObservabilityServiceQueryRangeBodyFromJSON(json: any): MetricsServiceObservabilityServiceQueryRangeBody {
    return MetricsServiceObservabilityServiceQueryRangeBodyFromJSONTyped(json, false);
}

export function MetricsServiceObservabilityServiceQueryRangeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceObservabilityServiceQueryRangeBody {
    if (json == null) {
        return json;
    }
    return {
        
        'queries': json['queries'] == null ? undefined : ((json['queries'] as Array<any>).map(CommonQueryFromJSON)),
        'formulas': json['formulas'] == null ? undefined : ((json['formulas'] as Array<any>).map(CommonFormulaFromJSON)),
        'samplesLimit': json['samplesLimit'] == null ? undefined : json['samplesLimit'],
        'timeRange': CommonTimeRangeLiteFromJSON(json['timeRange']),
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'version': json['version'] == null ? undefined : json['version'],
        'samplesOffset': json['samplesOffset'] == null ? undefined : json['samplesOffset'],
    };
}

  export function MetricsServiceObservabilityServiceQueryRangeBodyToJSON(json: any): MetricsServiceObservabilityServiceQueryRangeBody {
      return MetricsServiceObservabilityServiceQueryRangeBodyToJSONTyped(json, false);
  }

  export function MetricsServiceObservabilityServiceQueryRangeBodyToJSONTyped(value?: MetricsServiceObservabilityServiceQueryRangeBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queries': value['queries'] == null ? undefined : ((value['queries'] as Array<any>).map(CommonQueryToJSON)),
        'formulas': value['formulas'] == null ? undefined : ((value['formulas'] as Array<any>).map(CommonFormulaToJSON)),
        'samplesLimit': value['samplesLimit'],
        'timeRange': CommonTimeRangeLiteToJSON(value['timeRange']),
        'projectId': value['projectId'],
        'version': value['version'],
        'samplesOffset': value['samplesOffset'],
    };
}

