/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonFormula } from '../models/CommonFormula.js';
import { CommonQuery } from '../models/CommonQuery.js';
import { HttpFile } from '../http/http.js';

export class MetricsServiceObservabilityServiceQueryBody {
    'queries'?: Array<CommonQuery>;
    'formulas'?: Array<CommonFormula>;
    'time'?: string;
    'samplesLimit'?: number;
    'version'?: number;
    'timezone'?: string;
    'samplesOffset'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queries",
            "baseName": "queries",
            "type": "Array<CommonQuery>",
            "format": ""
        },
        {
            "name": "formulas",
            "baseName": "formulas",
            "type": "Array<CommonFormula>",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "string",
            "format": ""
        },
        {
            "name": "samplesLimit",
            "baseName": "samplesLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        },
        {
            "name": "samplesOffset",
            "baseName": "samplesOffset",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return MetricsServiceObservabilityServiceQueryBody.attributeTypeMap;
    }

    public constructor() {
    }
}
