/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface MetricsServiceMetricsQueryResponseMetric
 */
export interface MetricsServiceMetricsQueryResponseMetric {
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricsQueryResponseMetric
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MetricsServiceMetricsQueryResponseMetric
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceMetricsQueryResponseMetric
     */
    displayName?: string;
}

/**
 * Check if a given object implements the MetricsServiceMetricsQueryResponseMetric interface.
 */
export function instanceOfMetricsServiceMetricsQueryResponseMetric(value: object): value is MetricsServiceMetricsQueryResponseMetric {
    return true;
}

export function MetricsServiceMetricsQueryResponseMetricFromJSON(json: any): MetricsServiceMetricsQueryResponseMetric {
    return MetricsServiceMetricsQueryResponseMetricFromJSONTyped(json, false);
}

export function MetricsServiceMetricsQueryResponseMetricFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceMetricsQueryResponseMetric {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
    };
}

  export function MetricsServiceMetricsQueryResponseMetricToJSON(json: any): MetricsServiceMetricsQueryResponseMetric {
      return MetricsServiceMetricsQueryResponseMetricToJSONTyped(json, false);
  }

  export function MetricsServiceMetricsQueryResponseMetricToJSONTyped(value?: MetricsServiceMetricsQueryResponseMetric | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'labels': value['labels'],
        'displayName': value['displayName'],
    };
}

