/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetricsServiceMetricsQueryResponseSample } from './MetricsServiceMetricsQueryResponseSample';
import {
    MetricsServiceMetricsQueryResponseSampleFromJSON,
    MetricsServiceMetricsQueryResponseSampleFromJSONTyped,
    MetricsServiceMetricsQueryResponseSampleToJSON,
} from './MetricsServiceMetricsQueryResponseSample';

/**
 * 
 * @export
 * @interface MetricsServiceQueryValueResponseResult
 */
export interface MetricsServiceQueryValueResponseResult {
    /**
     * 
     * @type {Array<MetricsServiceMetricsQueryResponseSample>}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    sample?: Array<MetricsServiceMetricsQueryResponseSample>;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    alias?: string;
    /**
     * 
     * @type {string}
     * @memberof MetricsServiceQueryValueResponseResult
     */
    id?: string;
}

/**
 * Check if a given object implements the MetricsServiceQueryValueResponseResult interface.
 */
export function instanceOfMetricsServiceQueryValueResponseResult(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MetricsServiceQueryValueResponseResultFromJSON(json: any): MetricsServiceQueryValueResponseResult {
    return MetricsServiceQueryValueResponseResultFromJSONTyped(json, false);
}

export function MetricsServiceQueryValueResponseResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceQueryValueResponseResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'sample': !exists(json, 'sample') ? undefined : ((json['sample'] as Array<any>).map(MetricsServiceMetricsQueryResponseSampleFromJSON)),
        'error': !exists(json, 'error') ? undefined : json['error'],
        'alias': !exists(json, 'alias') ? undefined : json['alias'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function MetricsServiceQueryValueResponseResultToJSON(value?: MetricsServiceQueryValueResponseResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'sample': value.sample === undefined ? undefined : ((value.sample as Array<any>).map(MetricsServiceMetricsQueryResponseSampleToJSON)),
        'error': value.error,
        'alias': value.alias,
        'id': value.id,
    };
}

