/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricsServiceMetricInfoLabelValues
 */
export interface MetricsServiceMetricInfoLabelValues {
    /**
     * 
     * @type {Array<string>}
     * @memberof MetricsServiceMetricInfoLabelValues
     */
    values?: Array<string>;
}

/**
 * Check if a given object implements the MetricsServiceMetricInfoLabelValues interface.
 */
export function instanceOfMetricsServiceMetricInfoLabelValues(value: object): boolean {
    return true;
}

export function MetricsServiceMetricInfoLabelValuesFromJSON(json: any): MetricsServiceMetricInfoLabelValues {
    return MetricsServiceMetricInfoLabelValuesFromJSONTyped(json, false);
}

export function MetricsServiceMetricInfoLabelValuesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricsServiceMetricInfoLabelValues {
    if (json == null) {
        return json;
    }
    return {
        
        'values': json['values'] == null ? undefined : json['values'],
    };
}

export function MetricsServiceMetricInfoLabelValuesToJSON(value?: MetricsServiceMetricInfoLabelValues | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'values': value['values'],
    };
}

