/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PriceServiceBatchGetPricesResponseCoinPricePrice } from '../models/PriceServiceBatchGetPricesResponseCoinPricePrice.js';
import { PriceServiceCoinID } from '../models/PriceServiceCoinID.js';
import { HttpFile } from '../http/http.js';

export class PriceServiceBatchGetPricesResponseCoinPrice {
    'coinId'?: PriceServiceCoinID;
    'price'?: PriceServiceBatchGetPricesResponseCoinPricePrice;
    'error'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coinId",
            "baseName": "coinId",
            "type": "PriceServiceCoinID",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "PriceServiceBatchGetPricesResponseCoinPricePrice",
            "format": ""
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceServiceBatchGetPricesResponseCoinPrice.attributeTypeMap;
    }

    public constructor() {
    }
}
