/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PriceServiceBatchGetPricesResponseCoinPrice } from '../models/PriceServiceBatchGetPricesResponseCoinPrice.js';
import { HttpFile } from '../http/http.js';

export class PriceServiceBatchGetPricesResponse {
    'prices'?: Array<PriceServiceBatchGetPricesResponseCoinPrice>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "prices",
            "baseName": "prices",
            "type": "Array<PriceServiceBatchGetPricesResponseCoinPrice>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceServiceBatchGetPricesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
