/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonUserInfo } from './CommonUserInfo';
import {
    CommonUserInfoFromJSON,
    CommonUserInfoFromJSONTyped,
    CommonUserInfoToJSON,
} from './CommonUserInfo';
import type { ProcessorServiceChainState } from './ProcessorServiceChainState';
import {
    ProcessorServiceChainStateFromJSON,
    ProcessorServiceChainStateFromJSONTyped,
    ProcessorServiceChainStateToJSON,
} from './ProcessorServiceChainState';
import type { ProcessorServiceGetProcessorStatusResponseProcessorStatus } from './ProcessorServiceGetProcessorStatusResponseProcessorStatus';
import {
    ProcessorServiceGetProcessorStatusResponseProcessorStatusFromJSON,
    ProcessorServiceGetProcessorStatusResponseProcessorStatusFromJSONTyped,
    ProcessorServiceGetProcessorStatusResponseProcessorStatusToJSON,
} from './ProcessorServiceGetProcessorStatusResponseProcessorStatus';
import type { ProcessorServiceProcessorVersionState } from './ProcessorServiceProcessorVersionState';
import {
    ProcessorServiceProcessorVersionStateFromJSON,
    ProcessorServiceProcessorVersionStateFromJSONTyped,
    ProcessorServiceProcessorVersionStateToJSON,
} from './ProcessorServiceProcessorVersionState';

/**
 * 
 * @export
 * @interface ProcessorServiceGetProcessorStatusResponseProcessorEx
 */
export interface ProcessorServiceGetProcessorStatusResponseProcessorEx {
    /**
     * 
     * @type {Array<ProcessorServiceChainState>}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    states?: Array<ProcessorServiceChainState>;
    /**
     * 
     * @type {string}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    processorId?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    codeHash?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    commitSha?: string;
    /**
     * 
     * @type {CommonUserInfo}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    uploadedBy?: CommonUserInfo;
    /**
     * 
     * @type {Date}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    uploadedAt?: Date;
    /**
     * 
     * @type {ProcessorServiceGetProcessorStatusResponseProcessorStatus}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    processorStatus?: ProcessorServiceGetProcessorStatusResponseProcessorStatus;
    /**
     * 
     * @type {number}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    sdkVersion?: string;
    /**
     * 
     * @type {string}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    gitUrl?: string;
    /**
     * 
     * @type {ProcessorServiceProcessorVersionState}
     * @memberof ProcessorServiceGetProcessorStatusResponseProcessorEx
     */
    versionState?: ProcessorServiceProcessorVersionState;
}

/**
 * Check if a given object implements the ProcessorServiceGetProcessorStatusResponseProcessorEx interface.
 */
export function instanceOfProcessorServiceGetProcessorStatusResponseProcessorEx(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProcessorServiceGetProcessorStatusResponseProcessorExFromJSON(json: any): ProcessorServiceGetProcessorStatusResponseProcessorEx {
    return ProcessorServiceGetProcessorStatusResponseProcessorExFromJSONTyped(json, false);
}

export function ProcessorServiceGetProcessorStatusResponseProcessorExFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorServiceGetProcessorStatusResponseProcessorEx {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'states': !exists(json, 'states') ? undefined : ((json['states'] as Array<any>).map(ProcessorServiceChainStateFromJSON)),
        'processorId': !exists(json, 'processorId') ? undefined : json['processorId'],
        'codeHash': !exists(json, 'codeHash') ? undefined : json['codeHash'],
        'commitSha': !exists(json, 'commitSha') ? undefined : json['commitSha'],
        'uploadedBy': !exists(json, 'uploadedBy') ? undefined : CommonUserInfoFromJSON(json['uploadedBy']),
        'uploadedAt': !exists(json, 'uploadedAt') ? undefined : (new Date(json['uploadedAt'])),
        'processorStatus': !exists(json, 'processorStatus') ? undefined : ProcessorServiceGetProcessorStatusResponseProcessorStatusFromJSON(json['processorStatus']),
        'version': !exists(json, 'version') ? undefined : json['version'],
        'sdkVersion': !exists(json, 'sdkVersion') ? undefined : json['sdkVersion'],
        'gitUrl': !exists(json, 'gitUrl') ? undefined : json['gitUrl'],
        'versionState': !exists(json, 'versionState') ? undefined : ProcessorServiceProcessorVersionStateFromJSON(json['versionState']),
    };
}

export function ProcessorServiceGetProcessorStatusResponseProcessorExToJSON(value?: ProcessorServiceGetProcessorStatusResponseProcessorEx | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'states': value.states === undefined ? undefined : ((value.states as Array<any>).map(ProcessorServiceChainStateToJSON)),
        'processorId': value.processorId,
        'codeHash': value.codeHash,
        'commitSha': value.commitSha,
        'uploadedBy': CommonUserInfoToJSON(value.uploadedBy),
        'uploadedAt': value.uploadedAt === undefined ? undefined : (value.uploadedAt.toISOString()),
        'processorStatus': ProcessorServiceGetProcessorStatusResponseProcessorStatusToJSON(value.processorStatus),
        'version': value.version,
        'sdkVersion': value.sdkVersion,
        'gitUrl': value.gitUrl,
        'versionState': ProcessorServiceProcessorVersionStateToJSON(value.versionState),
    };
}

