/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonErrorRecord } from './CommonErrorRecord';
import {
    CommonErrorRecordFromJSON,
    CommonErrorRecordFromJSONTyped,
    CommonErrorRecordToJSON,
} from './CommonErrorRecord';
import type { ProcessorServiceChainStateStatusState } from './ProcessorServiceChainStateStatusState';
import {
    ProcessorServiceChainStateStatusStateFromJSON,
    ProcessorServiceChainStateStatusStateFromJSONTyped,
    ProcessorServiceChainStateStatusStateToJSON,
} from './ProcessorServiceChainStateStatusState';

/**
 * 
 * @export
 * @interface ProcessorServiceChainStateStatus
 */
export interface ProcessorServiceChainStateStatus {
    /**
     * 
     * @type {ProcessorServiceChainStateStatusState}
     * @memberof ProcessorServiceChainStateStatus
     */
    state?: ProcessorServiceChainStateStatusState;
    /**
     * 
     * @type {CommonErrorRecord}
     * @memberof ProcessorServiceChainStateStatus
     */
    errorRecord?: CommonErrorRecord;
}

/**
 * Check if a given object implements the ProcessorServiceChainStateStatus interface.
 */
export function instanceOfProcessorServiceChainStateStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProcessorServiceChainStateStatusFromJSON(json: any): ProcessorServiceChainStateStatus {
    return ProcessorServiceChainStateStatusFromJSONTyped(json, false);
}

export function ProcessorServiceChainStateStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorServiceChainStateStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : ProcessorServiceChainStateStatusStateFromJSON(json['state']),
        'errorRecord': !exists(json, 'errorRecord') ? undefined : CommonErrorRecordFromJSON(json['errorRecord']),
    };
}

export function ProcessorServiceChainStateStatusToJSON(value?: ProcessorServiceChainStateStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'state': ProcessorServiceChainStateStatusStateToJSON(value.state),
        'errorRecord': CommonErrorRecordToJSON(value.errorRecord),
    };
}

