/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ProcessorServiceGetProcessorStatusResponseProcessorStatusState = {
    Unknown: 'UNKNOWN',
    Error: 'ERROR',
    Starting: 'STARTING',
    Processing: 'PROCESSING',
    UnknownDefaultOpenApi: '11184809'
} as const;
export type ProcessorServiceGetProcessorStatusResponseProcessorStatusState = typeof ProcessorServiceGetProcessorStatusResponseProcessorStatusState[keyof typeof ProcessorServiceGetProcessorStatusResponseProcessorStatusState];


export function ProcessorServiceGetProcessorStatusResponseProcessorStatusStateFromJSON(json: any): ProcessorServiceGetProcessorStatusResponseProcessorStatusState {
    return ProcessorServiceGetProcessorStatusResponseProcessorStatusStateFromJSONTyped(json, false);
}

export function ProcessorServiceGetProcessorStatusResponseProcessorStatusStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProcessorServiceGetProcessorStatusResponseProcessorStatusState {
    return json as ProcessorServiceGetProcessorStatusResponseProcessorStatusState;
}

export function ProcessorServiceGetProcessorStatusResponseProcessorStatusStateToJSON(value?: ProcessorServiceGetProcessorStatusResponseProcessorStatusState | null): any {
    return value as any;
}

