/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CommonFormula } from './CommonFormula';
import {
    CommonFormulaFromJSON,
    CommonFormulaFromJSONTyped,
    CommonFormulaToJSON,
} from './CommonFormula';
import type { CommonQuery } from './CommonQuery';
import {
    CommonQueryFromJSON,
    CommonQueryFromJSONTyped,
    CommonQueryToJSON,
} from './CommonQuery';

/**
 * 
 * @export
 * @interface QueryRequest
 */
export interface QueryRequest {
    /**
     * 
     * @type {Array<CommonQuery>}
     * @memberof QueryRequest
     */
    queries?: Array<CommonQuery>;
    /**
     * 
     * @type {Array<CommonFormula>}
     * @memberof QueryRequest
     */
    formulas?: Array<CommonFormula>;
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    time?: string;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    samplesLimit?: number;
    /**
     * 
     * @type {number}
     * @memberof QueryRequest
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof QueryRequest
     */
    timezone?: string;
}

/**
 * Check if a given object implements the QueryRequest interface.
 */
export function instanceOfQueryRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function QueryRequestFromJSON(json: any): QueryRequest {
    return QueryRequestFromJSONTyped(json, false);
}

export function QueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'queries': !exists(json, 'queries') ? undefined : ((json['queries'] as Array<any>).map(CommonQueryFromJSON)),
        'formulas': !exists(json, 'formulas') ? undefined : ((json['formulas'] as Array<any>).map(CommonFormulaFromJSON)),
        'time': !exists(json, 'time') ? undefined : json['time'],
        'samplesLimit': !exists(json, 'samplesLimit') ? undefined : json['samplesLimit'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'timezone': !exists(json, 'timezone') ? undefined : json['timezone'],
    };
}

export function QueryRequestToJSON(value?: QueryRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'queries': value.queries === undefined ? undefined : ((value.queries as Array<any>).map(CommonQueryToJSON)),
        'formulas': value.formulas === undefined ? undefined : ((value.formulas as Array<any>).map(CommonFormulaToJSON)),
        'time': value.time,
        'samplesLimit': value.samplesLimit,
        'version': value.version,
        'timezone': value.timezone,
    };
}

