/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpec } from './SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpec.js';
import {
    SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecFromJSON,
    SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecFromJSONTyped,
    SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecToJSON,
    SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecToJSONTyped,
} from './SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpec.js';
import type { SolidityServiceSimulation } from './SolidityServiceSimulation.js';
import {
    SolidityServiceSimulationFromJSON,
    SolidityServiceSimulationFromJSONTyped,
    SolidityServiceSimulationToJSON,
    SolidityServiceSimulationToJSONTyped,
} from './SolidityServiceSimulation.js';

/**
 * 
 * @export
 * @interface SolidityServiceSolidityAPIServiceSimulateTransactionBody
 */
export interface SolidityServiceSolidityAPIServiceSimulateTransactionBody {
    /**
     * 
     * @type {SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpec}
     * @memberof SolidityServiceSolidityAPIServiceSimulateTransactionBody
     */
    chainSpec?: SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpec;
    /**
     * 
     * @type {SolidityServiceSimulation}
     * @memberof SolidityServiceSolidityAPIServiceSimulateTransactionBody
     */
    simulation: SolidityServiceSimulation;
}

/**
 * Check if a given object implements the SolidityServiceSolidityAPIServiceSimulateTransactionBody interface.
 */
export function instanceOfSolidityServiceSolidityAPIServiceSimulateTransactionBody(value: object): value is SolidityServiceSolidityAPIServiceSimulateTransactionBody {
    if (!('simulation' in value) || value['simulation'] === undefined) return false;
    return true;
}

export function SolidityServiceSolidityAPIServiceSimulateTransactionBodyFromJSON(json: any): SolidityServiceSolidityAPIServiceSimulateTransactionBody {
    return SolidityServiceSolidityAPIServiceSimulateTransactionBodyFromJSONTyped(json, false);
}

export function SolidityServiceSolidityAPIServiceSimulateTransactionBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceSolidityAPIServiceSimulateTransactionBody {
    if (json == null) {
        return json;
    }
    return {
        
        'chainSpec': json['chainSpec'] == null ? undefined : SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecFromJSON(json['chainSpec']),
        'simulation': SolidityServiceSimulationFromJSON(json['simulation']),
    };
}

  export function SolidityServiceSolidityAPIServiceSimulateTransactionBodyToJSON(json: any): SolidityServiceSolidityAPIServiceSimulateTransactionBody {
      return SolidityServiceSolidityAPIServiceSimulateTransactionBodyToJSONTyped(json, false);
  }

  export function SolidityServiceSolidityAPIServiceSimulateTransactionBodyToJSONTyped(value?: SolidityServiceSolidityAPIServiceSimulateTransactionBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chainSpec': SolidityServiceSolidityAPIServiceSimulateTransactionBodyChainSpecToJSON(value['chainSpec']),
        'simulation': SolidityServiceSimulationToJSON(value['simulation']),
    };
}

