/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class SolidityServiceGetTraceCallInternalRequestStateContext {
    'blockNumber'?: string;
    'transactionIndex'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionIndex",
            "baseName": "transactionIndex",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceGetTraceCallInternalRequestStateContext.attributeTypeMap;
    }

    public constructor() {
    }
}
