/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SolidityServiceFailure } from './SolidityServiceFailure';
import {
    SolidityServiceFailureFromJSON,
    SolidityServiceFailureFromJSONTyped,
    SolidityServiceFailureToJSON,
} from './SolidityServiceFailure';

/**
 * 
 * @export
 * @interface SolidityServiceCompileSourceInternalResponse
 */
export interface SolidityServiceCompileSourceInternalResponse {
    /**
     * 
     * @type {SolidityServiceFailure}
     * @memberof SolidityServiceCompileSourceInternalResponse
     */
    failure?: SolidityServiceFailure;
}

/**
 * Check if a given object implements the SolidityServiceCompileSourceInternalResponse interface.
 */
export function instanceOfSolidityServiceCompileSourceInternalResponse(value: object): boolean {
    return true;
}

export function SolidityServiceCompileSourceInternalResponseFromJSON(json: any): SolidityServiceCompileSourceInternalResponse {
    return SolidityServiceCompileSourceInternalResponseFromJSONTyped(json, false);
}

export function SolidityServiceCompileSourceInternalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceCompileSourceInternalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'failure': json['failure'] == null ? undefined : SolidityServiceFailureFromJSON(json['failure']),
    };
}

export function SolidityServiceCompileSourceInternalResponseToJSON(value?: SolidityServiceCompileSourceInternalResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'failure': SolidityServiceFailureToJSON(value['failure']),
    };
}

