/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SolidityServiceBaseChainConfig
 */
export interface SolidityServiceBaseChainConfig {
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    endpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    debugEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    sourceFetcherType?: string;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    sourceFetcherEndpoint?: string;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    sourceFetcherTimeout?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolidityServiceBaseChainConfig
     */
    sourceFetcherApiKeys?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceBaseChainConfig
     */
    oklinkChainShortName?: string;
}

/**
 * Check if a given object implements the SolidityServiceBaseChainConfig interface.
 */
export function instanceOfSolidityServiceBaseChainConfig(value: object): value is SolidityServiceBaseChainConfig {
    return true;
}

export function SolidityServiceBaseChainConfigFromJSON(json: any): SolidityServiceBaseChainConfig {
    return SolidityServiceBaseChainConfigFromJSONTyped(json, false);
}

export function SolidityServiceBaseChainConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceBaseChainConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'debugEndpoint': json['debugEndpoint'] == null ? undefined : json['debugEndpoint'],
        'sourceFetcherType': json['sourceFetcherType'] == null ? undefined : json['sourceFetcherType'],
        'sourceFetcherEndpoint': json['sourceFetcherEndpoint'] == null ? undefined : json['sourceFetcherEndpoint'],
        'sourceFetcherTimeout': json['sourceFetcherTimeout'] == null ? undefined : json['sourceFetcherTimeout'],
        'sourceFetcherApiKeys': json['sourceFetcherApiKeys'] == null ? undefined : json['sourceFetcherApiKeys'],
        'oklinkChainShortName': json['oklinkChainShortName'] == null ? undefined : json['oklinkChainShortName'],
    };
}

  export function SolidityServiceBaseChainConfigToJSON(json: any): SolidityServiceBaseChainConfig {
      return SolidityServiceBaseChainConfigToJSONTyped(json, false);
  }

  export function SolidityServiceBaseChainConfigToJSONTyped(value?: SolidityServiceBaseChainConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'debugEndpoint': value['debugEndpoint'],
        'sourceFetcherType': value['sourceFetcherType'],
        'sourceFetcherEndpoint': value['sourceFetcherEndpoint'],
        'sourceFetcherTimeout': value['sourceFetcherTimeout'],
        'sourceFetcherApiKeys': value['sourceFetcherApiKeys'],
        'oklinkChainShortName': value['oklinkChainShortName'],
    };
}

