/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolidityServiceUniversalSearchResultContract
 */
export interface SolidityServiceUniversalSearchResultContract {
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceUniversalSearchResultContract
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceUniversalSearchResultContract
     */
    contractName?: string;
}

/**
 * Check if a given object implements the SolidityServiceUniversalSearchResultContract interface.
 */
export function instanceOfSolidityServiceUniversalSearchResultContract(value: object): boolean {
    return true;
}

export function SolidityServiceUniversalSearchResultContractFromJSON(json: any): SolidityServiceUniversalSearchResultContract {
    return SolidityServiceUniversalSearchResultContractFromJSONTyped(json, false);
}

export function SolidityServiceUniversalSearchResultContractFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceUniversalSearchResultContract {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'] == null ? undefined : json['address'],
        'contractName': json['contractName'] == null ? undefined : json['contractName'],
    };
}

export function SolidityServiceUniversalSearchResultContractToJSON(value?: SolidityServiceUniversalSearchResultContract | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'contractName': value['contractName'],
    };
}

