/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SolidityServiceNodeEnvironment } from '../models/SolidityServiceNodeEnvironment.js';
import { SolidityServiceNodeForkConfig } from '../models/SolidityServiceNodeForkConfig.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceGetForkInfoResponse {
    'currentBlockNumber'?: string;
    'currentBlockTimestamp'?: string;
    'currentBlockHash'?: string;
    'hardFork'?: string;
    'transactionOrder'?: string;
    'environment'?: SolidityServiceNodeEnvironment;
    'forkConfig'?: SolidityServiceNodeForkConfig;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currentBlockNumber",
            "baseName": "currentBlockNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentBlockTimestamp",
            "baseName": "currentBlockTimestamp",
            "type": "string",
            "format": "uint64"
        },
        {
            "name": "currentBlockHash",
            "baseName": "currentBlockHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "hardFork",
            "baseName": "hardFork",
            "type": "string",
            "format": ""
        },
        {
            "name": "transactionOrder",
            "baseName": "transactionOrder",
            "type": "string",
            "format": ""
        },
        {
            "name": "environment",
            "baseName": "environment",
            "type": "SolidityServiceNodeEnvironment",
            "format": ""
        },
        {
            "name": "forkConfig",
            "baseName": "forkConfig",
            "type": "SolidityServiceNodeForkConfig",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceGetForkInfoResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
