/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SolidityServiceGetTraceCallInternalResponse
 */
export interface SolidityServiceGetTraceCallInternalResponse {
    /**
     * 
     * @type {Array<Array<object>>}
     * @memberof SolidityServiceGetTraceCallInternalResponse
     */
    result?: Array<Array<object>>;
    /**
     * 
     * @type {Array<Array<object>>}
     * @memberof SolidityServiceGetTraceCallInternalResponse
     */
    outputs?: Array<Array<object>>;
    /**
     * 
     * @type {string}
     * @memberof SolidityServiceGetTraceCallInternalResponse
     */
    error?: string;
}

/**
 * Check if a given object implements the SolidityServiceGetTraceCallInternalResponse interface.
 */
export function instanceOfSolidityServiceGetTraceCallInternalResponse(value: object): boolean {
    return true;
}

export function SolidityServiceGetTraceCallInternalResponseFromJSON(json: any): SolidityServiceGetTraceCallInternalResponse {
    return SolidityServiceGetTraceCallInternalResponseFromJSONTyped(json, false);
}

export function SolidityServiceGetTraceCallInternalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceGetTraceCallInternalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'result': json['result'] == null ? undefined : json['result'],
        'outputs': json['outputs'] == null ? undefined : json['outputs'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SolidityServiceGetTraceCallInternalResponseToJSON(value?: SolidityServiceGetTraceCallInternalResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'result': value['result'],
        'outputs': value['outputs'],
        'error': value['error'],
    };
}

