/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SolidityServiceChainIdentifier } from '../models/SolidityServiceChainIdentifier.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceManagedFork {
    'parentChainSpec'?: SolidityServiceChainIdentifier;
    'parentRpcEndpoint'?: string;
    'parentBlockNumber'?: string;
    'chainId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "parentChainSpec",
            "baseName": "parentChainSpec",
            "type": "SolidityServiceChainIdentifier",
            "format": ""
        },
        {
            "name": "parentRpcEndpoint",
            "baseName": "parentRpcEndpoint",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentBlockNumber",
            "baseName": "parentBlockNumber",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "chainId",
            "baseName": "chainId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceManagedFork.attributeTypeMap;
    }

    public constructor() {
    }
}
