/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EvmTransaction } from '../models/EvmTransaction.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceEvmRawTransaction {
    'hash'?: string;
    'blockNumber'?: string;
    'isIn'?: boolean;
    'trace'?: boolean;
    'tx'?: EvmTransaction;
    'json'?: string;
    'timestamp'?: string;
    'transactionStatus'?: number;
    'methodSignature'?: string;
    'methodSignatureText'?: string;
    'abiItem'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string",
            "format": ""
        },
        {
            "name": "blockNumber",
            "baseName": "blockNumber",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "isIn",
            "baseName": "isIn",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "trace",
            "baseName": "trace",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tx",
            "baseName": "tx",
            "type": "EvmTransaction",
            "format": ""
        },
        {
            "name": "json",
            "baseName": "json",
            "type": "string",
            "format": ""
        },
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": "int64"
        },
        {
            "name": "transactionStatus",
            "baseName": "transactionStatus",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "methodSignature",
            "baseName": "methodSignature",
            "type": "string",
            "format": ""
        },
        {
            "name": "methodSignatureText",
            "baseName": "methodSignatureText",
            "type": "string",
            "format": ""
        },
        {
            "name": "abiItem",
            "baseName": "abiItem",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceEvmRawTransaction.attributeTypeMap;
    }

    public constructor() {
    }
}
