/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
/**
 * 
 * @export
 * @interface SolidityServicePreProcessCompilationInternalResponse
 */
export interface SolidityServicePreProcessCompilationInternalResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SolidityServicePreProcessCompilationInternalResponse
     */
    preprocessedAddresses?: Array<string>;
}

/**
 * Check if a given object implements the SolidityServicePreProcessCompilationInternalResponse interface.
 */
export function instanceOfSolidityServicePreProcessCompilationInternalResponse(value: object): boolean {
    return true;
}

export function SolidityServicePreProcessCompilationInternalResponseFromJSON(json: any): SolidityServicePreProcessCompilationInternalResponse {
    return SolidityServicePreProcessCompilationInternalResponseFromJSONTyped(json, false);
}

export function SolidityServicePreProcessCompilationInternalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServicePreProcessCompilationInternalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'preprocessedAddresses': json['preprocessedAddresses'] == null ? undefined : json['preprocessedAddresses'],
    };
}

export function SolidityServicePreProcessCompilationInternalResponseToJSON(value?: SolidityServicePreProcessCompilationInternalResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'preprocessedAddresses': value['preprocessedAddresses'],
    };
}

