/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolidityServiceFailure } from './SolidityServiceFailure.js';
import {
    SolidityServiceFailureFromJSON,
    SolidityServiceFailureFromJSONTyped,
    SolidityServiceFailureToJSON,
    SolidityServiceFailureToJSONTyped,
} from './SolidityServiceFailure.js';

/**
 * 
 * @export
 * @interface SolidityServiceFetchAndCompileInternalResponse
 */
export interface SolidityServiceFetchAndCompileInternalResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof SolidityServiceFetchAndCompileInternalResponse
     */
    compiledAddresses?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: SolidityServiceFailure; }}
     * @memberof SolidityServiceFetchAndCompileInternalResponse
     */
    failures?: { [key: string]: SolidityServiceFailure; };
}

/**
 * Check if a given object implements the SolidityServiceFetchAndCompileInternalResponse interface.
 */
export function instanceOfSolidityServiceFetchAndCompileInternalResponse(value: object): value is SolidityServiceFetchAndCompileInternalResponse {
    return true;
}

export function SolidityServiceFetchAndCompileInternalResponseFromJSON(json: any): SolidityServiceFetchAndCompileInternalResponse {
    return SolidityServiceFetchAndCompileInternalResponseFromJSONTyped(json, false);
}

export function SolidityServiceFetchAndCompileInternalResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceFetchAndCompileInternalResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'compiledAddresses': json['compiledAddresses'] == null ? undefined : json['compiledAddresses'],
        'failures': json['failures'] == null ? undefined : (mapValues(json['failures'], SolidityServiceFailureFromJSON)),
    };
}

  export function SolidityServiceFetchAndCompileInternalResponseToJSON(json: any): SolidityServiceFetchAndCompileInternalResponse {
      return SolidityServiceFetchAndCompileInternalResponseToJSONTyped(json, false);
  }

  export function SolidityServiceFetchAndCompileInternalResponseToJSONTyped(value?: SolidityServiceFetchAndCompileInternalResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'compiledAddresses': value['compiledAddresses'],
        'failures': value['failures'] == null ? undefined : (mapValues(value['failures'], SolidityServiceFailureToJSON)),
    };
}

