/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolidityServiceUniversalSearchResult } from './SolidityServiceUniversalSearchResult.js';
import {
    SolidityServiceUniversalSearchResultFromJSON,
    SolidityServiceUniversalSearchResultFromJSONTyped,
    SolidityServiceUniversalSearchResultToJSON,
} from './SolidityServiceUniversalSearchResult.js';

/**
 * 
 * @export
 * @interface SolidityServiceUniversalSearchResponse
 */
export interface SolidityServiceUniversalSearchResponse {
    /**
     * 
     * @type {Array<SolidityServiceUniversalSearchResult>}
     * @memberof SolidityServiceUniversalSearchResponse
     */
    results?: Array<SolidityServiceUniversalSearchResult>;
}

/**
 * Check if a given object implements the SolidityServiceUniversalSearchResponse interface.
 */
export function instanceOfSolidityServiceUniversalSearchResponse(value: object): boolean {
    return true;
}

export function SolidityServiceUniversalSearchResponseFromJSON(json: any): SolidityServiceUniversalSearchResponse {
    return SolidityServiceUniversalSearchResponseFromJSONTyped(json, false);
}

export function SolidityServiceUniversalSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceUniversalSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SolidityServiceUniversalSearchResultFromJSON)),
    };
}

export function SolidityServiceUniversalSearchResponseToJSON(value?: SolidityServiceUniversalSearchResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SolidityServiceUniversalSearchResultToJSON)),
    };
}

