/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SolidityServiceCompilerOptions } from '../models/SolidityServiceCompilerOptions.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceSourceInfo {
    'contractName'?: string;
    'options'?: SolidityServiceCompilerOptions;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contractName",
            "baseName": "contractName",
            "type": "string",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "SolidityServiceCompilerOptions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceSourceInfo.attributeTypeMap;
    }

    public constructor() {
    }
}
