/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SolidityServiceMetadata } from '../models/SolidityServiceMetadata.js';
import { SolidityServiceOptimizer } from '../models/SolidityServiceOptimizer.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceSettings {
    'remappings'?: Array<string>;
    'optimizer'?: SolidityServiceOptimizer;
    'evmVersion'?: string;
    'metadata'?: SolidityServiceMetadata;
    'viaIR'?: boolean;
    'compilationTarget'?: { [key: string]: string; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "remappings",
            "baseName": "remappings",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "optimizer",
            "baseName": "optimizer",
            "type": "SolidityServiceOptimizer",
            "format": ""
        },
        {
            "name": "evmVersion",
            "baseName": "evmVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "SolidityServiceMetadata",
            "format": ""
        },
        {
            "name": "viaIR",
            "baseName": "viaIR",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "compilationTarget",
            "baseName": "compilationTarget",
            "type": "{ [key: string]: string; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceSettings.attributeTypeMap;
    }

    public constructor() {
    }
}
