/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SolidityServiceSourceMultiFile } from '../models/SolidityServiceSourceMultiFile.js';
import { HttpFile } from '../http/http.js';

export class SolidityServiceSourceSpec {
    'id'?: string;
    'multiFile'?: SolidityServiceSourceMultiFile;
    'standardJson'?: any;
    'metadata'?: any;
    'solidityVersion'?: string;
    'contractName'?: string;
    'constructorArgs'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "multiFile",
            "baseName": "multiFile",
            "type": "SolidityServiceSourceMultiFile",
            "format": ""
        },
        {
            "name": "standardJson",
            "baseName": "standardJson",
            "type": "any",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "any",
            "format": ""
        },
        {
            "name": "solidityVersion",
            "baseName": "solidityVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "contractName",
            "baseName": "contractName",
            "type": "string",
            "format": ""
        },
        {
            "name": "constructorArgs",
            "baseName": "constructorArgs",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SolidityServiceSourceSpec.attributeTypeMap;
    }

    public constructor() {
    }
}
