/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolidityServiceBlockOverrides } from './SolidityServiceBlockOverrides.js';
import {
    SolidityServiceBlockOverridesFromJSON,
    SolidityServiceBlockOverridesFromJSONTyped,
    SolidityServiceBlockOverridesToJSON,
} from './SolidityServiceBlockOverrides.js';

/**
 * 
 * @export
 * @interface SolidityServiceGetTraceCallInternalRequestBundle
 */
export interface SolidityServiceGetTraceCallInternalRequestBundle {
    /**
     * 
     * @type {Array<object>}
     * @memberof SolidityServiceGetTraceCallInternalRequestBundle
     */
    transactions?: Array<object>;
    /**
     * 
     * @type {SolidityServiceBlockOverrides}
     * @memberof SolidityServiceGetTraceCallInternalRequestBundle
     */
    blockOverride?: SolidityServiceBlockOverrides;
}

/**
 * Check if a given object implements the SolidityServiceGetTraceCallInternalRequestBundle interface.
 */
export function instanceOfSolidityServiceGetTraceCallInternalRequestBundle(value: object): boolean {
    return true;
}

export function SolidityServiceGetTraceCallInternalRequestBundleFromJSON(json: any): SolidityServiceGetTraceCallInternalRequestBundle {
    return SolidityServiceGetTraceCallInternalRequestBundleFromJSONTyped(json, false);
}

export function SolidityServiceGetTraceCallInternalRequestBundleFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceGetTraceCallInternalRequestBundle {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': json['transactions'] == null ? undefined : json['transactions'],
        'blockOverride': json['blockOverride'] == null ? undefined : SolidityServiceBlockOverridesFromJSON(json['blockOverride']),
    };
}

export function SolidityServiceGetTraceCallInternalRequestBundleToJSON(value?: SolidityServiceGetTraceCallInternalRequestBundle | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transactions': value['transactions'],
        'blockOverride': SolidityServiceBlockOverridesToJSON(value['blockOverride']),
    };
}

