/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { SolidityServiceFork } from './SolidityServiceFork.js';
import {
    SolidityServiceForkFromJSON,
    SolidityServiceForkFromJSONTyped,
    SolidityServiceForkToJSON,
    SolidityServiceForkToJSONTyped,
} from './SolidityServiceFork.js';

/**
 * 
 * @export
 * @interface SolidityServiceForkServiceUpdateForkBody
 */
export interface SolidityServiceForkServiceUpdateForkBody {
    /**
     * 
     * @type {SolidityServiceFork}
     * @memberof SolidityServiceForkServiceUpdateForkBody
     */
    fork: SolidityServiceFork;
}

/**
 * Check if a given object implements the SolidityServiceForkServiceUpdateForkBody interface.
 */
export function instanceOfSolidityServiceForkServiceUpdateForkBody(value: object): value is SolidityServiceForkServiceUpdateForkBody {
    if (!('fork' in value) || value['fork'] === undefined) return false;
    return true;
}

export function SolidityServiceForkServiceUpdateForkBodyFromJSON(json: any): SolidityServiceForkServiceUpdateForkBody {
    return SolidityServiceForkServiceUpdateForkBodyFromJSONTyped(json, false);
}

export function SolidityServiceForkServiceUpdateForkBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): SolidityServiceForkServiceUpdateForkBody {
    if (json == null) {
        return json;
    }
    return {
        
        'fork': SolidityServiceForkFromJSON(json['fork']),
    };
}

  export function SolidityServiceForkServiceUpdateForkBodyToJSON(json: any): SolidityServiceForkServiceUpdateForkBody {
      return SolidityServiceForkServiceUpdateForkBodyToJSONTyped(json, false);
  }

  export function SolidityServiceForkServiceUpdateForkBodyToJSONTyped(value?: SolidityServiceForkServiceUpdateForkBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'fork': SolidityServiceForkToJSON(value['fork']),
    };
}

