/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { EvmTransaction } from './EvmTransaction.js';
import {
    EvmTransactionFromJSON,
    EvmTransactionFromJSONTyped,
    EvmTransactionToJSON,
} from './EvmTransaction.js';

/**
 * 
 * @export
 * @interface TxindexEvmRawTransaction
 */
export interface TxindexEvmRawTransaction {
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    hash?: string;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    blockNumber?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TxindexEvmRawTransaction
     */
    isIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TxindexEvmRawTransaction
     */
    trace?: boolean;
    /**
     * 
     * @type {EvmTransaction}
     * @memberof TxindexEvmRawTransaction
     */
    tx?: EvmTransaction;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    json?: string;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    timestamp?: string;
    /**
     * 
     * @type {number}
     * @memberof TxindexEvmRawTransaction
     */
    transactionStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    methodSignature?: string;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    methodSignatureText?: string;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmRawTransaction
     */
    abiItem?: string;
}

/**
 * Check if a given object implements the TxindexEvmRawTransaction interface.
 */
export function instanceOfTxindexEvmRawTransaction(value: object): boolean {
    return true;
}

export function TxindexEvmRawTransactionFromJSON(json: any): TxindexEvmRawTransaction {
    return TxindexEvmRawTransactionFromJSONTyped(json, false);
}

export function TxindexEvmRawTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxindexEvmRawTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'hash': json['hash'] == null ? undefined : json['hash'],
        'blockNumber': json['blockNumber'] == null ? undefined : json['blockNumber'],
        'isIn': json['isIn'] == null ? undefined : json['isIn'],
        'trace': json['trace'] == null ? undefined : json['trace'],
        'tx': json['tx'] == null ? undefined : EvmTransactionFromJSON(json['tx']),
        'json': json['json'] == null ? undefined : json['json'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'transactionStatus': json['transactionStatus'] == null ? undefined : json['transactionStatus'],
        'methodSignature': json['methodSignature'] == null ? undefined : json['methodSignature'],
        'methodSignatureText': json['methodSignatureText'] == null ? undefined : json['methodSignatureText'],
        'abiItem': json['abiItem'] == null ? undefined : json['abiItem'],
    };
}

export function TxindexEvmRawTransactionToJSON(value?: TxindexEvmRawTransaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'hash': value['hash'],
        'blockNumber': value['blockNumber'],
        'isIn': value['isIn'],
        'trace': value['trace'],
        'tx': EvmTransactionToJSON(value['tx']),
        'json': value['json'],
        'timestamp': value['timestamp'],
        'transactionStatus': value['transactionStatus'],
        'methodSignature': value['methodSignature'],
        'methodSignatureText': value['methodSignatureText'],
        'abiItem': value['abiItem'],
    };
}

