/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TxindexEvmRawTransaction } from './TxindexEvmRawTransaction';
import {
    TxindexEvmRawTransactionFromJSON,
    TxindexEvmRawTransactionFromJSONTyped,
    TxindexEvmRawTransactionToJSON,
} from './TxindexEvmRawTransaction';

/**
 * 
 * @export
 * @interface TxindexEvmSearchTransactionsResponse
 */
export interface TxindexEvmSearchTransactionsResponse {
    /**
     * 
     * @type {Array<TxindexEvmRawTransaction>}
     * @memberof TxindexEvmSearchTransactionsResponse
     */
    transactions?: Array<TxindexEvmRawTransaction>;
    /**
     * 
     * @type {string}
     * @memberof TxindexEvmSearchTransactionsResponse
     */
    nextPageToken?: string;
}

/**
 * Check if a given object implements the TxindexEvmSearchTransactionsResponse interface.
 */
export function instanceOfTxindexEvmSearchTransactionsResponse(value: object): boolean {
    return true;
}

export function TxindexEvmSearchTransactionsResponseFromJSON(json: any): TxindexEvmSearchTransactionsResponse {
    return TxindexEvmSearchTransactionsResponseFromJSONTyped(json, false);
}

export function TxindexEvmSearchTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TxindexEvmSearchTransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(TxindexEvmRawTransactionFromJSON)),
        'nextPageToken': json['nextPageToken'] == null ? undefined : json['nextPageToken'],
    };
}

export function TxindexEvmSearchTransactionsResponseToJSON(value?: TxindexEvmSearchTransactionsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(TxindexEvmRawTransactionToJSON)),
        'nextPageToken': value['nextPageToken'],
    };
}

