/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebServiceListExternalDashboardsRequestNameTagsFilter } from './WebServiceListExternalDashboardsRequestNameTagsFilter';
import {
    WebServiceListExternalDashboardsRequestNameTagsFilterFromJSON,
    WebServiceListExternalDashboardsRequestNameTagsFilterFromJSONTyped,
    WebServiceListExternalDashboardsRequestNameTagsFilterToJSON,
} from './WebServiceListExternalDashboardsRequestNameTagsFilter';
import type { WebServiceListExternalDashboardsRequestOrderBy } from './WebServiceListExternalDashboardsRequestOrderBy';
import {
    WebServiceListExternalDashboardsRequestOrderByFromJSON,
    WebServiceListExternalDashboardsRequestOrderByFromJSONTyped,
    WebServiceListExternalDashboardsRequestOrderByToJSON,
} from './WebServiceListExternalDashboardsRequestOrderBy';

/**
 * 
 * @export
 * @interface WebServiceListExternalDashboardsRequest
 */
export interface WebServiceListExternalDashboardsRequest {
    /**
     * 
     * @type {string}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    ownerName?: string;
    /**
     * 
     * @type {string}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    ownerFilter?: string;
    /**
     * 
     * @type {WebServiceListExternalDashboardsRequestNameTagsFilter}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    tagsFilter?: WebServiceListExternalDashboardsRequestNameTagsFilter;
    /**
     * 
     * @type {boolean}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    starFilter?: boolean;
    /**
     * 
     * @type {WebServiceListExternalDashboardsRequestOrderBy}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    orderBy?: WebServiceListExternalDashboardsRequestOrderBy;
    /**
     * 
     * @type {string}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    orderByTimeRange?: string;
    /**
     * 
     * @type {number}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    limit?: number;
    /**
     * 
     * @type {number}
     * @memberof WebServiceListExternalDashboardsRequest
     */
    offset?: number;
}

/**
 * Check if a given object implements the WebServiceListExternalDashboardsRequest interface.
 */
export function instanceOfWebServiceListExternalDashboardsRequest(value: object): boolean {
    return true;
}

export function WebServiceListExternalDashboardsRequestFromJSON(json: any): WebServiceListExternalDashboardsRequest {
    return WebServiceListExternalDashboardsRequestFromJSONTyped(json, false);
}

export function WebServiceListExternalDashboardsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceListExternalDashboardsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'ownerName': json['ownerName'] == null ? undefined : json['ownerName'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'ownerFilter': json['ownerFilter'] == null ? undefined : json['ownerFilter'],
        'tagsFilter': json['tagsFilter'] == null ? undefined : WebServiceListExternalDashboardsRequestNameTagsFilterFromJSON(json['tagsFilter']),
        'starFilter': json['starFilter'] == null ? undefined : json['starFilter'],
        'orderBy': json['orderBy'] == null ? undefined : WebServiceListExternalDashboardsRequestOrderByFromJSON(json['orderBy']),
        'orderByTimeRange': json['orderByTimeRange'] == null ? undefined : json['orderByTimeRange'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'offset': json['offset'] == null ? undefined : json['offset'],
    };
}

export function WebServiceListExternalDashboardsRequestToJSON(value?: WebServiceListExternalDashboardsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'projectId': value['projectId'],
        'ownerName': value['ownerName'],
        'slug': value['slug'],
        'ownerFilter': value['ownerFilter'],
        'tagsFilter': WebServiceListExternalDashboardsRequestNameTagsFilterToJSON(value['tagsFilter']),
        'starFilter': value['starFilter'],
        'orderBy': WebServiceListExternalDashboardsRequestOrderByToJSON(value['orderBy']),
        'orderByTimeRange': value['orderByTimeRange'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

