/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class WebServiceChartConfigColorTheme {
    'textColor'?: string;
    'backgroundColor'?: string;
    'themeType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "textColor",
            "baseName": "textColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "backgroundColor",
            "baseName": "backgroundColor",
            "type": "string",
            "format": ""
        },
        {
            "name": "themeType",
            "baseName": "themeType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceChartConfigColorTheme.attributeTypeMap;
    }

    public constructor() {
    }
}
