/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebServiceDashboardSharing
 */
export interface WebServiceDashboardSharing {
    /**
     * 
     * @type {string}
     * @memberof WebServiceDashboardSharing
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof WebServiceDashboardSharing
     */
    dashboardId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WebServiceDashboardSharing
     */
    isPublic?: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof WebServiceDashboardSharing
     */
    viewers?: Array<string>;
}

/**
 * Check if a given object implements the WebServiceDashboardSharing interface.
 */
export function instanceOfWebServiceDashboardSharing(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebServiceDashboardSharingFromJSON(json: any): WebServiceDashboardSharing {
    return WebServiceDashboardSharingFromJSONTyped(json, false);
}

export function WebServiceDashboardSharingFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceDashboardSharing {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'dashboardId': !exists(json, 'dashboardId') ? undefined : json['dashboardId'],
        'isPublic': !exists(json, 'isPublic') ? undefined : json['isPublic'],
        'viewers': !exists(json, 'viewers') ? undefined : json['viewers'],
    };
}

export function WebServiceDashboardSharingToJSON(value?: WebServiceDashboardSharing | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'dashboardId': value.dashboardId,
        'isPublic': value.isPublic,
        'viewers': value.viewers,
    };
}

