/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebServiceDashboardLayouts } from '../models/WebServiceDashboardLayouts.js';
import { HttpFile } from '../http/http.js';

export class WebServiceDashboardResponsiveLayouts {
    'responsiveLayouts'?: { [key: string]: WebServiceDashboardLayouts; };

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "responsiveLayouts",
            "baseName": "responsiveLayouts",
            "type": "{ [key: string]: WebServiceDashboardLayouts; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceDashboardResponsiveLayouts.attributeTypeMap;
    }

    public constructor() {
    }
}
