/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebServiceDashboardLayoutsLayout
 */
export interface WebServiceDashboardLayoutsLayout {
    /**
     * 
     * @type {string}
     * @memberof WebServiceDashboardLayoutsLayout
     */
    i?: string;
    /**
     * 
     * @type {number}
     * @memberof WebServiceDashboardLayoutsLayout
     */
    x?: number;
    /**
     * 
     * @type {number}
     * @memberof WebServiceDashboardLayoutsLayout
     */
    y?: number;
    /**
     * 
     * @type {number}
     * @memberof WebServiceDashboardLayoutsLayout
     */
    w?: number;
    /**
     * 
     * @type {number}
     * @memberof WebServiceDashboardLayoutsLayout
     */
    h?: number;
}

/**
 * Check if a given object implements the WebServiceDashboardLayoutsLayout interface.
 */
export function instanceOfWebServiceDashboardLayoutsLayout(value: object): boolean {
    return true;
}

export function WebServiceDashboardLayoutsLayoutFromJSON(json: any): WebServiceDashboardLayoutsLayout {
    return WebServiceDashboardLayoutsLayoutFromJSONTyped(json, false);
}

export function WebServiceDashboardLayoutsLayoutFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceDashboardLayoutsLayout {
    if (json == null) {
        return json;
    }
    return {
        
        'i': json['i'] == null ? undefined : json['i'],
        'x': json['x'] == null ? undefined : json['x'],
        'y': json['y'] == null ? undefined : json['y'],
        'w': json['w'] == null ? undefined : json['w'],
        'h': json['h'] == null ? undefined : json['h'],
    };
}

export function WebServiceDashboardLayoutsLayoutToJSON(value?: WebServiceDashboardLayoutsLayout | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'i': value['i'],
        'x': value['x'],
        'y': value['y'],
        'w': value['w'],
        'h': value['h'],
    };
}

