/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommonEventLogConfig } from '../models/CommonEventLogConfig.js';
import { WebServiceEventLogsConfigTimeRangeOverride } from '../models/WebServiceEventLogsConfigTimeRangeOverride.js';
import { HttpFile } from '../http/http.js';

export class WebServiceEventLogsConfig {
    'columnsConfig'?: CommonEventLogConfig;
    'timeRangeOverride'?: WebServiceEventLogsConfigTimeRangeOverride;
    'query'?: string;
    'sourceName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "columnsConfig",
            "baseName": "columnsConfig",
            "type": "CommonEventLogConfig",
            "format": ""
        },
        {
            "name": "timeRangeOverride",
            "baseName": "timeRangeOverride",
            "type": "WebServiceEventLogsConfigTimeRangeOverride",
            "format": ""
        },
        {
            "name": "query",
            "baseName": "query",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceName",
            "baseName": "sourceName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceEventLogsConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
