/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime.js';
import type { WebServiceChartConfigColorTheme } from './WebServiceChartConfigColorTheme.js';
import {
    WebServiceChartConfigColorThemeFromJSON,
    WebServiceChartConfigColorThemeFromJSONTyped,
    WebServiceChartConfigColorThemeToJSON,
} from './WebServiceChartConfigColorTheme.js';

/**
 * 
 * @export
 * @interface WebServiceChartConfigMappingRule
 */
export interface WebServiceChartConfigMappingRule {
    /**
     * 
     * @type {string}
     * @memberof WebServiceChartConfigMappingRule
     */
    comparison?: string;
    /**
     * 
     * @type {number}
     * @memberof WebServiceChartConfigMappingRule
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof WebServiceChartConfigMappingRule
     */
    text?: string;
    /**
     * 
     * @type {WebServiceChartConfigColorTheme}
     * @memberof WebServiceChartConfigMappingRule
     */
    colorTheme?: WebServiceChartConfigColorTheme;
}

/**
 * Check if a given object implements the WebServiceChartConfigMappingRule interface.
 */
export function instanceOfWebServiceChartConfigMappingRule(value: object): boolean {
    return true;
}

export function WebServiceChartConfigMappingRuleFromJSON(json: any): WebServiceChartConfigMappingRule {
    return WebServiceChartConfigMappingRuleFromJSONTyped(json, false);
}

export function WebServiceChartConfigMappingRuleFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceChartConfigMappingRule {
    if (json == null) {
        return json;
    }
    return {
        
        'comparison': json['comparison'] == null ? undefined : json['comparison'],
        'value': json['value'] == null ? undefined : json['value'],
        'text': json['text'] == null ? undefined : json['text'],
        'colorTheme': json['colorTheme'] == null ? undefined : WebServiceChartConfigColorThemeFromJSON(json['colorTheme']),
    };
}

export function WebServiceChartConfigMappingRuleToJSON(value?: WebServiceChartConfigMappingRule | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comparison': value['comparison'],
        'value': value['value'],
        'text': value['text'],
        'colorTheme': WebServiceChartConfigColorThemeToJSON(value['colorTheme']),
    };
}

