/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WebServiceChartConfigCalculation } from './WebServiceChartConfigCalculation';
import {
    WebServiceChartConfigCalculationFromJSON,
    WebServiceChartConfigCalculationFromJSONTyped,
    WebServiceChartConfigCalculationToJSON,
} from './WebServiceChartConfigCalculation';
import type { WebServiceChartConfigDirection } from './WebServiceChartConfigDirection';
import {
    WebServiceChartConfigDirectionFromJSON,
    WebServiceChartConfigDirectionFromJSONTyped,
    WebServiceChartConfigDirectionToJSON,
} from './WebServiceChartConfigDirection';
import type { WebServiceChartConfigSort } from './WebServiceChartConfigSort';
import {
    WebServiceChartConfigSortFromJSON,
    WebServiceChartConfigSortFromJSONTyped,
    WebServiceChartConfigSortToJSON,
} from './WebServiceChartConfigSort';

/**
 * 
 * @export
 * @interface WebServiceChartConfigBarGaugeConfig
 */
export interface WebServiceChartConfigBarGaugeConfig {
    /**
     * 
     * @type {WebServiceChartConfigDirection}
     * @memberof WebServiceChartConfigBarGaugeConfig
     */
    direction?: WebServiceChartConfigDirection;
    /**
     * 
     * @type {WebServiceChartConfigCalculation}
     * @memberof WebServiceChartConfigBarGaugeConfig
     */
    calculation?: WebServiceChartConfigCalculation;
    /**
     * 
     * @type {WebServiceChartConfigSort}
     * @memberof WebServiceChartConfigBarGaugeConfig
     */
    sort?: WebServiceChartConfigSort;
}

/**
 * Check if a given object implements the WebServiceChartConfigBarGaugeConfig interface.
 */
export function instanceOfWebServiceChartConfigBarGaugeConfig(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebServiceChartConfigBarGaugeConfigFromJSON(json: any): WebServiceChartConfigBarGaugeConfig {
    return WebServiceChartConfigBarGaugeConfigFromJSONTyped(json, false);
}

export function WebServiceChartConfigBarGaugeConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceChartConfigBarGaugeConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'direction': !exists(json, 'direction') ? undefined : WebServiceChartConfigDirectionFromJSON(json['direction']),
        'calculation': !exists(json, 'calculation') ? undefined : WebServiceChartConfigCalculationFromJSON(json['calculation']),
        'sort': !exists(json, 'sort') ? undefined : WebServiceChartConfigSortFromJSON(json['sort']),
    };
}

export function WebServiceChartConfigBarGaugeConfigToJSON(value?: WebServiceChartConfigBarGaugeConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'direction': WebServiceChartConfigDirectionToJSON(value.direction),
        'calculation': WebServiceChartConfigCalculationToJSON(value.calculation),
        'sort': WebServiceChartConfigSortToJSON(value.sort),
    };
}

