/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebServiceDashboardResult } from './WebServiceDashboardResult';
import {
    WebServiceDashboardResultFromJSON,
    WebServiceDashboardResultFromJSONTyped,
    WebServiceDashboardResultToJSON,
} from './WebServiceDashboardResult';

/**
 * 
 * @export
 * @interface WebServiceGetExternalDashboardResponse
 */
export interface WebServiceGetExternalDashboardResponse {
    /**
     * 
     * @type {WebServiceDashboardResult}
     * @memberof WebServiceGetExternalDashboardResponse
     */
    dashboard?: WebServiceDashboardResult;
}

/**
 * Check if a given object implements the WebServiceGetExternalDashboardResponse interface.
 */
export function instanceOfWebServiceGetExternalDashboardResponse(value: object): boolean {
    return true;
}

export function WebServiceGetExternalDashboardResponseFromJSON(json: any): WebServiceGetExternalDashboardResponse {
    return WebServiceGetExternalDashboardResponseFromJSONTyped(json, false);
}

export function WebServiceGetExternalDashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceGetExternalDashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboard': json['dashboard'] == null ? undefined : WebServiceDashboardResultFromJSON(json['dashboard']),
    };
}

export function WebServiceGetExternalDashboardResponseToJSON(value?: WebServiceGetExternalDashboardResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dashboard': WebServiceDashboardResultToJSON(value['dashboard']),
    };
}

