/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebServiceDashboard } from './WebServiceDashboard';
import {
    WebServiceDashboardFromJSON,
    WebServiceDashboardFromJSONTyped,
    WebServiceDashboardToJSON,
} from './WebServiceDashboard';

/**
 * 
 * @export
 * @interface WebServiceImportDashboardResponse
 */
export interface WebServiceImportDashboardResponse {
    /**
     * 
     * @type {WebServiceDashboard}
     * @memberof WebServiceImportDashboardResponse
     */
    dashboard?: WebServiceDashboard;
}

/**
 * Check if a given object implements the WebServiceImportDashboardResponse interface.
 */
export function instanceOfWebServiceImportDashboardResponse(value: object): boolean {
    return true;
}

export function WebServiceImportDashboardResponseFromJSON(json: any): WebServiceImportDashboardResponse {
    return WebServiceImportDashboardResponseFromJSONTyped(json, false);
}

export function WebServiceImportDashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceImportDashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'dashboard': json['dashboard'] == null ? undefined : WebServiceDashboardFromJSON(json['dashboard']),
    };
}

export function WebServiceImportDashboardResponseToJSON(value?: WebServiceImportDashboardResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'dashboard': WebServiceDashboardToJSON(value['dashboard']),
    };
}

