/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WebServiceChartConfigCalculation } from '../models/WebServiceChartConfigCalculation.js';
import { WebServiceChartConfigDirection } from '../models/WebServiceChartConfigDirection.js';
import { WebServiceChartConfigSort } from '../models/WebServiceChartConfigSort.js';
import { HttpFile } from '../http/http.js';

export class WebServiceChartConfigBarGaugeConfig {
    'direction'?: WebServiceChartConfigDirection;
    'calculation'?: WebServiceChartConfigCalculation;
    'sort'?: WebServiceChartConfigSort;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "direction",
            "baseName": "direction",
            "type": "WebServiceChartConfigDirection",
            "format": ""
        },
        {
            "name": "calculation",
            "baseName": "calculation",
            "type": "WebServiceChartConfigCalculation",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "WebServiceChartConfigSort",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceChartConfigBarGaugeConfig.attributeTypeMap;
    }

    public constructor() {
    }
}


