/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebServiceChartConfigDirection = {
    Horizontal: 'HORIZONTAL',
    Vertical: 'VERTICAL'
} as const;
export type WebServiceChartConfigDirection = typeof WebServiceChartConfigDirection[keyof typeof WebServiceChartConfigDirection];


export function instanceOfWebServiceChartConfigDirection(value: any): boolean {
    for (const key in WebServiceChartConfigDirection) {
        if (Object.prototype.hasOwnProperty.call(WebServiceChartConfigDirection, key)) {
            if (WebServiceChartConfigDirection[key as keyof typeof WebServiceChartConfigDirection] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WebServiceChartConfigDirectionFromJSON(json: any): WebServiceChartConfigDirection {
    return WebServiceChartConfigDirectionFromJSONTyped(json, false);
}

export function WebServiceChartConfigDirectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceChartConfigDirection {
    return json as WebServiceChartConfigDirection;
}

export function WebServiceChartConfigDirectionToJSON(value?: WebServiceChartConfigDirection | null): any {
    return value as any;
}

export function WebServiceChartConfigDirectionToJSONTyped(value: any, ignoreDiscriminator: boolean): WebServiceChartConfigDirection {
    return value as WebServiceChartConfigDirection;
}

