/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class WebServiceImportDashboardRequest {
    /**
    * The id of the target dashboard to import into.
    */
    'dashboardId': string;
    /**
    * The json data of a previously exported dashboard.
    */
    'dashboardJson': any;
    /**
    * Override the layout of target dashboard.
    */
    'overrideLayouts'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dashboardId",
            "baseName": "dashboardId",
            "type": "string",
            "format": ""
        },
        {
            "name": "dashboardJson",
            "baseName": "dashboardJson",
            "type": "any",
            "format": ""
        },
        {
            "name": "overrideLayouts",
            "baseName": "overrideLayouts",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceImportDashboardRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
