/**
 * Sentio API
 * Sentio Open API for query data
 *
 * OpenAPI spec version: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class WebServiceChartConfigYAxisConfig {
    'min'?: string;
    'max'?: string;
    'scale'?: boolean;
    'stacked'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "min",
            "baseName": "min",
            "type": "string",
            "format": ""
        },
        {
            "name": "max",
            "baseName": "max",
            "type": "string",
            "format": ""
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stacked",
            "baseName": "stacked",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WebServiceChartConfigYAxisConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
