/* tslint:disable */
/* eslint-disable */
/**
 * Sentio API
 * Sentio Open API for query data
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const WebServiceNoteVerticalAlignment = {
    Top: 'TOP',
    Middle: 'MIDDLE',
    Bottom: 'BOTTOM'
} as const;
export type WebServiceNoteVerticalAlignment = typeof WebServiceNoteVerticalAlignment[keyof typeof WebServiceNoteVerticalAlignment];


export function instanceOfWebServiceNoteVerticalAlignment(value: any): boolean {
    return Object.values(WebServiceNoteVerticalAlignment).includes(value);
}

export function WebServiceNoteVerticalAlignmentFromJSON(json: any): WebServiceNoteVerticalAlignment {
    return WebServiceNoteVerticalAlignmentFromJSONTyped(json, false);
}

export function WebServiceNoteVerticalAlignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebServiceNoteVerticalAlignment {
    return json as WebServiceNoteVerticalAlignment;
}

export function WebServiceNoteVerticalAlignmentToJSON(value?: WebServiceNoteVerticalAlignment | null): any {
    return value as any;
}

